---
title: "\n"
output: html_document
---

```{r cube, echo=FALSE, eval=TRUE, include=FALSE, results="hide", messages=FALSE}
# load packages
library(ncdf4)
library(maptools)
library(raster)
library(rasterVis)
library(RColorBrewer)
library(cubeview)
```

```{r read tr21, echo=FALSE, eval=TRUE, results="hide", warning=FALSE}
# read TraCE21-ka transient climate-model simulation decadal data
tr21dec_path <- "/Users/bartlein/Projects/ESSD/data/nc_files/"
tr21dec_name <- "Trace21_TREFHT_anm2.nc"
tr21dec_file <- paste(tr21dec_path, tr21dec_name, sep="")
tas_anm_ann <- brick(tr21dec_file, varname="tas_anm_ann", band=seq(1:2204))
tas_anm_ann <- rotate(tas_anm_ann)
```

```{r tr21 subset, echo=FALSE}
tas2 <- subset(tas_anm_ann, subset=seq(1,2201, by=10))
```

```{r plot setup, echo=FALSE}
mapTheme <- rasterTheme(region=(rev(brewer.pal(10,"RdBu"))))
cutpts <- c(-40,-10,-5,-2,-1,0,1,2,5,10,20)
col <- rev(brewer.pal(10,"RdBu"))
# levelplot(subset(tas2,1), at=cutpts, margin=FALSE, par.settings=mapTheme)
```

```{r tr21 cube, echo=FALSE}
cubeView(tas2, at=cutpts, col.regions=col)
```

## TraCE-21ka Temperature Anomalies ## 

```{r}
print(" ")
```
