<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Regression 2 – Multiple regression</title>

<script src="site_libs/header-attrs-2.25/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/clipboard-1.7.1/clipboard.min.js"></script>
<link href="site_libs/primer-tooltips-1.4.0/build.css" rel="stylesheet" />
<link href="site_libs/klippy-0.0.0.9500/css/klippy.min.css" rel="stylesheet" />
<script src="site_libs/klippy-0.0.0.9500/js/klippy.min.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; } /* Alert */
code span.an { color: #008000; } /* Annotation */
code span.at { } /* Attribute */
code span.bu { } /* BuiltIn */
code span.cf { color: #0000ff; } /* ControlFlow */
code span.ch { color: #008080; } /* Char */
code span.cn { } /* Constant */
code span.co { color: #008000; } /* Comment */
code span.cv { color: #008000; } /* CommentVar */
code span.do { color: #008000; } /* Documentation */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.im { } /* Import */
code span.in { color: #008000; } /* Information */
code span.kw { color: #0000ff; } /* Keyword */
code span.op { } /* Operator */
code span.ot { color: #ff4000; } /* Other */
code span.pp { color: #ff4000; } /* Preprocessor */
code span.sc { color: #008080; } /* SpecialChar */
code span.ss { color: #008080; } /* SpecialString */
code span.st { color: #008080; } /* String */
code span.va { } /* Variable */
code span.vs { color: #008080; } /* VerbatimString */
code span.wa { color: #008000; font-weight: bold; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<link rel="stylesheet" href="html-md-01.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">R for Earth-System Science</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="overview.html">Overview</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Topics
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Lecture topics</li>
    <li>
      <a href="intro.html">Introduction: R, RStudio, and other infrastructure</a>
    </li>
    <li>
      <a href="usingR.html">Using R</a>
    </li>
    <li>
      <a href="ESSdata.html">Earth-system science data</a>
    </li>
    <li>
      <a href="netCDF.html">netCDF in R</a>
    </li>
    <li>
      <a href="netcdf_terra.html">netCDF and terra</a>
    </li>
    <li>
      <a href="plots1.html">Plots (1)</a>
    </li>
    <li>
      <a href="plots2.html">Plots (2)</a>
    </li>
    <li>
      <a href="maps1.html">Maps (1)</a>
    </li>
    <li>
      <a href="maps2.html">Maps (2)</a>
    </li>
    <li>
      <a href="geospatial.html">Geospatial analyses</a>
    </li>
    <li>
      <a href="regression1.html">Regression and correlation</a>
    </li>
    <li>
      <a href="regression2.html">Regression 2</a>
    </li>
    <li>
      <a href="pca.html">PCA</a>
    </li>
    <li>
      <a href="svd.html">Singular Value Decomposistion</a>
    </li>
    <li>
      <a href="highdim.html">High-resolution &amp; high-dimensional data</a>
    </li>
    <li>
      <a href="multivariate.html">Multivariate methods</a>
    </li>
    <li>
      <a href="timeseries.html">Time-series analysis</a>
    </li>
    <li class="dropdown-header">Other topics</li>
    <li>
      <a href="sf_stars_sftime.html">sf / stars / sftime</a>
    </li>
    <li>
      <a href="hdf5_intro.html">HDF in R</a>
    </li>
    <li>
      <a href="anomalies.html">Long-term means and anomalies</a>
    </li>
    <li>
      <a href="tsplots.html">Time-series plots</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Tasks
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li class="dropdown-header">Tasks</li>
    <li>
      <a href="installR.html">Install R and RStudio</a>
    </li>
    <li>
      <a href="Ex_UsingR.html">Using R exercise</a>
    </li>
    <li>
      <a href="install_netCDF.html">Install netCDF &amp; Panoply</a>
    </li>
    <li>
      <a href="transfer.html">File transfer</a>
    </li>
    <li>
      <a href="texteditor.html">Install a text editor</a>
    </li>
    <li>
      <a href="dataselection.html">Project data set selection</a>
    </li>
    <li>
      <a href="markdown.html">Markdown and RMarkdown</a>
    </li>
    <li>
      <a href="scripts_and_md.html">R Scripts and R Markdown</a>
    </li>
    <li>
      <a href="github.html">GitHub</a>
    </li>
    <li>
      <a href="pages.html">pages.uoregon.edu</a>
    </li>
    <li>
      <a href="localweb.html">Local websites</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Other
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="readings.html">Readings</a>
    </li>
    <li>
      <a href="websites.html">Old course web pages</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="about.html">About</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Regression 2 – Multiple regression</h1>

</div>

<div id="TOC">
<ul>
<li><a href="#introduction" id="toc-introduction"><span
class="toc-section-number">1</span> Introduction</a></li>
<li><a href="#fitting-a-multiple-regression-equation"
id="toc-fitting-a-multiple-regression-equation"><span
class="toc-section-number">2</span> Fitting a multiple regression
equation</a></li>
<li><a href="#regression-assumptions"
id="toc-regression-assumptions"><span
class="toc-section-number">3</span> Regression Assumptions</a>
<ul>
<li><a href="#consequences-of-assumption-violations"
id="toc-consequences-of-assumption-violations"><span
class="toc-section-number">3.1</span> Consequences of assumption
violations</a></li>
</ul></li>
<li><a href="#example-noaa-global-land-ocean-temperatures"
id="toc-example-noaa-global-land-ocean-temperatures"><span
class="toc-section-number">4</span> Example – NOAA Global Land + Ocean
temperatures</a>
<ul>
<li><a href="#read-the-noaa-data" id="toc-read-the-noaa-data"><span
class="toc-section-number">4.1</span> Read the NOAA data</a></li>
<li><a href="#simple-linear-regression-lm_01"
id="toc-simple-linear-regression-lm_01"><span
class="toc-section-number">4.2</span> Simple linear regression
(lm_01)</a>
<ul>
<li><a href="#eye-balling-the-influence-of-enso-on-the-regression-model"
id="toc-eye-balling-the-influence-of-enso-on-the-regression-model"><span
class="toc-section-number">4.2.1</span> Eye-balling the influence of
ENSO on the regression model</a></li>
</ul></li>
<li><a href="#dummy-variable-regression-lm_02"
id="toc-dummy-variable-regression-lm_02"><span
class="toc-section-number">4.3</span> Dummy-variable regression
(lm_02)</a></li>
<li><a
href="#dummy-variable-regression-both-intercept-and-slope-varying-lm_03"
id="toc-dummy-variable-regression-both-intercept-and-slope-varying-lm_03"><span
class="toc-section-number">4.4</span> Dummy-variable regression, both
intercept and slope varying (lm_03)</a></li>
</ul></li>
<li><a href="#a-model-with-co2-as-the-predictor-variable"
id="toc-a-model-with-co2-as-the-predictor-variable"><span
class="toc-section-number">5</span> A model with CO<sub>2</sub> as the
predictor variable</a>
<ul>
<li><a href="#simple-linear-regression-co2-as-a-predictor-lm_05"
id="toc-simple-linear-regression-co2-as-a-predictor-lm_05"><span
class="toc-section-number">5.1</span> Simple linear regression,
CO<sub>2</sub> as a predictor (lm_05)</a></li>
<li><a
href="#dummy-variable-regression-intercepts-only-co2-as-a-predictor-lm_06"
id="toc-dummy-variable-regression-intercepts-only-co2-as-a-predictor-lm_06"><span
class="toc-section-number">5.2</span> Dummy-variable regression,
intercepts-only, CO<sub>2</sub> as a predictor (lm_06)</a></li>
</ul></li>
<li><a href="#curvilinear-trends" id="toc-curvilinear-trends"><span
class="toc-section-number">6</span> Curvilinear trends</a>
<ul>
<li><a href="#a-simple-polynomial-trend-lm_07"
id="toc-a-simple-polynomial-trend-lm_07"><span
class="toc-section-number">6.1</span> A simple polynomial trend
(lm_07)</a></li>
<li><a href="#a-polynomial-dummy-variable-regression-lm_08"
id="toc-a-polynomial-dummy-variable-regression-lm_08"><span
class="toc-section-number">6.2</span> A polynomial dummy-variable
regression (lm_08)</a></li>
</ul></li>
<li><a href="#a-regression-model-with-autocorrelated-residuals"
id="toc-a-regression-model-with-autocorrelated-residuals"><span
class="toc-section-number">7</span> A regression model with
autocorrelated residuals</a>
<ul>
<li><a href="#set-up" id="toc-set-up"><span
class="toc-section-number">7.1</span> Set up</a></li>
<li><a href="#time-series-regression-model"
id="toc-time-series-regression-model"><span
class="toc-section-number">7.2</span> Time-series regression
model</a></li>
<li><a href="#slope-of-the-polynomial-trend"
id="toc-slope-of-the-polynomial-trend"><span
class="toc-section-number">7.3</span> Slope of the polynomial
trend</a></li>
</ul></li>
</ul>
</div>

<script>
  addClassKlippyTo("pre.r, pre.markdown");
  addKlippy('right', 'top', 'auto', '1', 'Copy code', 'Copied!');
</script>
<p>
<span style="color: #00cc00;">NOTE: This page has been revised for
Winter 2024, but may undergo further edits.</span>
</p>
<div id="introduction" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Introduction</h1>
<p>Multiple regression is (conceptually) a simple extension of bivariate
regression, in which the influence of more than one predictor variable
on the response can be estimated. For the case with two predictor
variables, the analysis can be thought of as involving the fitting of a
plane (as opposed to a line in the bivariate regression case), and the
equations for the OLS estimates of the regression equations are only a
little more complicated algebraically. For three or more predictors, the
algebra is also quite simple, but requires the use of matrix
algebra.</p>
<p>A couple of illustrations jointly describe the idea of fitting a
plane:</p>
<ul>
<li><a
href="https://pjbartlein.github.io/REarthSysSci/images/nwk7_1.gif">fitting
a plane using two predictor variables</a></li>
<li><a
href="https://pjbartlein.github.io/REarthSysSci/images/mreg.gif">one
data point and its deviation from the regression plane or response
surface</a></li>
</ul>
</div>
<div id="fitting-a-multiple-regression-equation" class="section level1"
number="2">
<h1><span class="header-section-number">2</span> Fitting a multiple
regression equation</h1>
<p>The mathematics behind multiple regression analysis is more
complicated than that for bivariate regression, but can be elegantly
presented using matrix algebra</p>
<ul>
<li><a
href="https://pjbartlein.github.io/REarthSysSci/topics/matrix.pdf">matrix
algebra</a></li>
<li><a
href="https://pjbartlein.github.io/REarthSysSci/topics/matreg.html">regression
analysis in matrix algebra terms</a></li>
</ul>
<p>The following example provide a short illustration of the use of
matrix algebra to obtain the regression coefficients.<br />
The example data set for illustrating the use of regression diagnostics
(<code>/Users/bartlein/projects/RESS/data/csv_files/</code>) is used
here, in particular, the multiple regression using <code>x1</code> and
<code>x2</code> as predictors for the response variable
<code>y5</code></p>
<p>Read the data:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="co"># read regrex3.csv</span></span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="co"># modify the following path to reflect local files</span></span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a>csv_path <span class="ot">&lt;-</span> <span class="st">&quot;/Users/bartlein/projects/RESS/data/csv_files/&quot;</span></span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a>csv_name <span class="ot">&lt;-</span> <span class="st">&quot;regrex3.csv&quot;</span></span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a>csv_file <span class="ot">&lt;-</span> <span class="fu">paste</span>(csv_path, csv_name, <span class="at">sep=</span><span class="st">&quot;&quot;</span>)</span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a>regrex3 <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(csv_file) </span></code></pre></div>
<p>First, take a look at the different variables in the example data
set.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="co"># regrex3</span></span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a><span class="fu">attach</span>(regrex3)</span>
<span id="cb2-3"><a href="#cb2-3" tabindex="-1"></a><span class="fu">summary</span>(regrex3)</span></code></pre></div>
<pre><code>##     Obs.no.             x1                x2               y1               y2               y3        
##  Min.   :  1.00   Min.   : 0.2076   Min.   :-9.794   Min.   :-7.580   Min.   :-6.739   Min.   :-7.735  
##  1st Qu.: 25.75   1st Qu.: 7.6887   1st Qu.:16.850   1st Qu.: 2.104   1st Qu.: 2.580   1st Qu.: 1.761  
##  Median : 50.50   Median :15.1511   Median :27.546   Median :10.098   Median :10.002   Median :10.487  
##  Mean   : 50.50   Mean   :14.0750   Mean   :28.468   Mean   : 9.513   Mean   : 9.513   Mean   : 9.473  
##  3rd Qu.: 75.25   3rd Qu.:20.4470   3rd Qu.:40.138   3rd Qu.:17.263   3rd Qu.:16.819   3rd Qu.:17.126  
##  Max.   :100.00   Max.   :24.9525   Max.   :63.861   Max.   :24.217   Max.   :24.459   Max.   :24.168  
##        y4               y5         
##  Min.   :-2.097   Min.   : -8.455  
##  1st Qu.: 2.256   1st Qu.: 45.818  
##  Median : 9.483   Median : 76.446  
##  Mean   : 9.716   Mean   : 73.884  
##  3rd Qu.:16.588   3rd Qu.:102.690  
##  Max.   :24.217   Max.   :150.621</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">cbind</span>(y5,x1,x2))</span></code></pre></div>
<pre><code>##            y5      x1      x2
## [1,]  99.4237 17.6403 39.2009
## [2,]  47.8476  9.3786 20.2735
## [3,]  89.1535 20.0313 33.7959
## [4,] 143.1316 23.4556 48.6115
## [5,] 124.6998 24.4938 47.3454
## [6,]  51.5796  8.8475 18.0954</code></pre>
<p>Create an <em>n</em> row by 1 column matrix (i.e. a column vector)
called <strong>y</strong>:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="co"># create the column vector y</span></span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(y5)</span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">matrix</span>(y5, <span class="at">nrow=</span>n, <span class="at">ncol=</span><span class="dv">1</span>)</span>
<span id="cb6-4"><a href="#cb6-4" tabindex="-1"></a><span class="fu">dim</span>(y)</span></code></pre></div>
<pre><code>## [1] 100   1</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="fu">head</span>(y)</span></code></pre></div>
<pre><code>##          [,1]
## [1,]  99.4237
## [2,]  47.8476
## [3,]  89.1535
## [4,] 143.1316
## [5,] 124.6998
## [6,]  51.5796</code></pre>
<p>Create an <em>n</em> row by <em>p</em>+1 matrix, <strong>X</strong>,
with 1’s in the first column, and <code>x1</code> and <code>x2</code> in
the second and third columns:</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a><span class="co"># create the predictor-variable matrix</span></span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="fu">cbind</span>(<span class="fu">rep</span>(<span class="dv">1</span>,n),x1,x2), <span class="at">nrow=</span>n, <span class="at">ncol=</span><span class="dv">3</span>)</span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a><span class="fu">dim</span>(X)</span></code></pre></div>
<pre><code>## [1] 100   3</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="fu">head</span>(X)</span></code></pre></div>
<pre><code>##      [,1]    [,2]    [,3]
## [1,]    1 17.6403 39.2009
## [2,]    1  9.3786 20.2735
## [3,]    1 20.0313 33.7959
## [4,]    1 23.4556 48.6115
## [5,]    1 24.4938 47.3454
## [6,]    1  8.8475 18.0954</code></pre>
<p>Now use matrix algebra to calculate <strong>b</strong>, the
<em>p</em>+1 row by 1 column matrix (e.g. a column vector) of regression
coefficients, <em>b</em><sub>0</sub>, <em>b</em><sub>1</sub> and
<em>b</em><sub>2</sub>: <strong>b</strong> =
(<strong>X’X</strong>)<sup>-1</sup><strong>X’y</strong>.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a><span class="co"># calculate the regression coefficients</span></span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">solve</span>(<span class="fu">t</span>(X) <span class="sc">%*%</span> X) <span class="sc">%*%</span> (<span class="fu">t</span>(X) <span class="sc">%*%</span> y)</span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a><span class="fu">print</span>(b)</span></code></pre></div>
<pre><code>##           [,1]
## [1,] 3.4159624
## [2,] 0.9241464
## [3,] 2.0184663</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a><span class="fu">dim</span>(b)</span></code></pre></div>
<pre><code>## [1] 3 1</code></pre>
<p>The matrix functions and operators used in the above expression
include <code>t()</code>, which transposes a matrix, <code>%*%</code>,
which is the matrix multiplication operator, and <code>solve()</code>,
which inverts a matrix.</p>
<p>Compare these values with those obtained using the <code>lm()</code>
function:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a><span class="co"># linear model with lm()</span></span>
<span id="cb18-2"><a href="#cb18-2" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(y5 <span class="sc">~</span> x1<span class="sc">+</span>x2, <span class="at">data=</span>regrex3)</span>
<span id="cb18-3"><a href="#cb18-3" tabindex="-1"></a>lm1</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = y5 ~ x1 + x2, data = regrex3)
## 
## Coefficients:
## (Intercept)           x1           x2  
##      3.4160       0.9241       2.0185</code></pre>
<p>Now calculate the fitted values (<em>y-hats</em>), i.e. <span
class="math inline">\(\mathbf{\widehat{y}}\)</span> =
<strong>Xb</strong>:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="co"># matrix fitted values</span></span>
<span id="cb20-2"><a href="#cb20-2" tabindex="-1"></a>yhat <span class="ot">&lt;-</span> X <span class="sc">%*%</span> b</span></code></pre></div>
<p>and compare these with those obtained using the <code>lm()</code>
function</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">cbind</span>(yhat,lm1<span class="sc">$</span>fitted.values))</span></code></pre></div>
<pre><code>##        [,1]      [,2]
## 1  98.84388  98.84388
## 2  53.00454  53.00454
## 3  90.14370  90.14370
## 4 123.21305 123.21305
## 5 121.61691 121.61691
## 6  48.11730  48.11730</code></pre>
<p>In addition to being able to efficiently represent the derivation of
terms and their properties in regression analysis in general, matrix
algebra also provides a an efficient way of doing the actual
calculations.</p>
<p><a href="regression2.html">[Back to top]</a></p>
</div>
<div id="regression-assumptions" class="section level1" number="3">
<h1><span class="header-section-number">3</span> Regression
Assumptions</h1>
<p>The basic regression model (as well as more complicated ones) have
certain underlying assumptions, violations of which have an impact on
the optimality of the fitted model, i.e., the extent to which the model
and its parameters represent the best model that can be fit, that is,
the one that performs the best in the tasks of representing the
relationship between the response variable and the predictor
variable(s), or predicting future values of the response variable given
new values of the predictor variables.</p>
<p>The main assumptions that underlie regression analysis:</p>
<ul>
<li>the prediction errors or residuals are assumed to be independent,
identically normally distributed random variables, with a mean of 0 and
a standard deviation of <em>s</em>,</li>
<li>the <em>X</em>’s (predictor or independent variables) are known
without error,</li>
<li>the <em>X</em>’s are not correlated.</li>
<li>the correct model has been specified (i.e. the right predictors have
been included in the model.</li>
</ul>
<p>If the assumptions are not violated, then the Gauss-Markov theorem
indicates that the usual OLS estimates are optimal in the sense of being
unbiased and having minimum variance. If one or more of the assumptions
are violated, then estimated regression coefficients may be biased
(i.e. they may be systematically in error), and not minimum variance
(i.e. there may be more uncertainty in the coefficients than is apparent
from the results).</p>
<div id="consequences-of-assumption-violations" class="section level2"
number="3.1">
<h2><span class="header-section-number">3.1</span> Consequences of
assumption violations</h2>
<p>If the assumptions are violated, then there may be two
consequences–the estimated coefficients may be biased
(i.e. systematically wrong), and they may longer have minimum variance
(i.e. their uncertainty increases).</p>
<ul>
<li>the notion of variability of the regression coefficients</li>
<li>illustrations using repeated simulations of data sets with built-in
assumption violations <a
href="https://pjbartlein.github.io/REarthSysSci/images/violate1.gif">[examples]</a>,
<a
href="https://pjbartlein.github.io/REarthSysSci/images/violate2.gif">[solutions]</a></li>
</ul>
<p><a href="regression2.html">[Back to top]</a></p>
</div>
</div>
<div id="example-noaa-global-land-ocean-temperatures"
class="section level1" number="4">
<h1><span class="header-section-number">4</span> Example – NOAA Global
Land + Ocean temperatures</h1>
<p>It’s plain to see that Earth’s average temperature is increasing
(e.g. <a
href="https://www.ncei.noaa.gov/access/monitoring/monthly-report/global/202313">[NOAA
2023 Global Climate Report]</a>. (See the second figure.) One issue that
arises is the estimation of the rate of temperature increase, and
whether the rate is also changing over time. One factor that complicates
that assessment is ENSO (El Niño Southern Oscillation), the variations
in temperature of the tropical Pacific Ocean <a
href="https://www.climate.gov/enso">[https://www.climate.gov/enso]</a>,
between warm phases (El Niño) and cool phases (La Niña). In addition to
the influence of ENSO on atmospheric circulation across the Pacific,
owing to the large surface area of the Pacific Ocean, ENSO may influence
global average temperatures, locally (in time) increasing them during
warm phases (El Niño) and locally decreasing them during cool phases (La
Niña) (<a
href="https://www.ncei.noaa.gov/access/monitoring/monthly-report/global/202313">[NOAA
2023 Global Climate Report]</a>. See the third figure.)</p>
<p>Because both things are going at at once (the trend toward increasing
temperature overall, and the local ENSO-related increases and
decreases), it’s difficult to quantitatively assess or separate the
trend and local variability from the inspection of figures alone. That’s
where quantitative estimation using regression comes in. The information
for colorizing the 1950-present monthly temperature plot comes from the
<a
href="https://www.climate.gov/news-features/understanding-climate/climate-variability-oceanic-nino-index">[Oceanic
Niño Index]</a>, a composite of several tropical Pacific sea-surface
temperature (SST) indices, which has been detrended. The data are from
<a href="https://www.cpc.ncep.noaa.gov/data/indices/oni.ascii.txt">[ONI
data]</a>, see here for the data in tabular form <a
href="https://origin.cpc.ncep.noaa.gov/products/analysis_monitoring/ensostuff/ONI_v5.php">[ONI
data table]</a>.</p>
<p>In addition to the ONI data, we’ll also use the <a
href="https://www.ncei.noaa.gov/access/monitoring/climate-at-a-glance/global/time-series/globe/land_ocean/ytd/12/1850-2023">[NOAA
Global Monthly Land + Ocean time series]</a> (back to 1950). Because the
trend in global temperatures is not mechanistically controlled by time,
but is controlled by CO<sub>2</sub>, we’ll also use the monthly
Scripps/NOAA CO<sub>2</sub> trends data <a
href="https://gml.noaa.gov/ccgg/trends/">[https://gml.noaa.gov/ccgg/trends/]</a>
(March 1958 onward). The data can be found here: <a
href="https://gml.noaa.gov/webdata/ccgg/trends/co2/co2_mm_mlo.txt">[NOAA
CO<sub>2</sub> Trends]</a>. The input data set
(<code>NOAA_Globe_T_ENSO_CO2_1950-2023.csv</code>) contains the year,
month, decimal year, temperatures of the land, ocean, and land plus
ocean, the ONI monthly total value, the anomaly and code, and the
monthly mean CO<sub>2</sub>, the deseasonalized CO<sub>2</sub> value,
and their difference (the “local” CO<sub>2</sub> anomaly.)</p>
<div id="read-the-noaa-data" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> Read the NOAA
data</h2>
<p>Load libraries</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb23-2"><a href="#cb23-2" tabindex="-1"></a><span class="fu">library</span>(forecast)</span></code></pre></div>
<pre><code>## Registered S3 method overwritten by &#39;quantmod&#39;:
##   method            from
##   as.zoo.data.frame zoo</code></pre>
<p>Read the data, modifying paths as necessary:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" tabindex="-1"></a><span class="co"># read NOAA monthly temperature, ONI (ENSO), and CO2</span></span>
<span id="cb25-2"><a href="#cb25-2" tabindex="-1"></a><span class="co"># modify the following path to reflect local files</span></span>
<span id="cb25-3"><a href="#cb25-3" tabindex="-1"></a>csv_path <span class="ot">&lt;-</span> <span class="st">&quot;/Users/bartlein/projects/RESS/data/csv_files/&quot;</span></span>
<span id="cb25-4"><a href="#cb25-4" tabindex="-1"></a>csv_name <span class="ot">&lt;-</span> <span class="st">&quot;NOAA_Globe_T_ENSO_CO2_1950-2023.csv&quot;</span></span>
<span id="cb25-5"><a href="#cb25-5" tabindex="-1"></a>csv_file <span class="ot">&lt;-</span> <span class="fu">paste</span>(csv_path, csv_name, <span class="at">sep=</span><span class="st">&quot;&quot;</span>)</span>
<span id="cb25-6"><a href="#cb25-6" tabindex="-1"></a>NOAA <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(csv_file) </span>
<span id="cb25-7"><a href="#cb25-7" tabindex="-1"></a><span class="fu">str</span>(NOAA)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    888 obs. of  12 variables:
##  $ Year         : int  1950 1950 1950 1950 1950 1950 1950 1950 1950 1950 ...
##  $ Month        : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ YrMn         : num  1950 1950 1950 1950 1950 ...
##  $ T_Land       : num  -0.733 -0.961 -0.514 -0.671 -0.343 ...
##  $ T_Ocean      : num  -0.421 -0.438 -0.398 -0.411 -0.352 ...
##  $ T_LandOcean  : num  -0.518 -0.6 -0.434 -0.492 -0.349 ...
##  $ ONI_total    : num  24.7 25.2 25.8 26.1 26.3 ...
##  $ ONI_anm      : num  -1.53 -1.34 -1.16 -1.18 -1.07 -0.85 -0.54 -0.42 -0.39 -0.44 ...
##  $ ONI_code     : chr  &quot;La Niña&quot; &quot;La Niña&quot; &quot;La Niña&quot; &quot;La Niña&quot; ...
##  $ CO2_mean     : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ CO2_deseas   : num  NA NA NA NA NA NA NA NA NA NA ...
##  $ CO2_local_anm: num  NA NA NA NA NA NA NA NA NA NA ...</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a><span class="fu">summary</span>(NOAA)</span></code></pre></div>
<pre><code>##       Year          Month            YrMn          T_Land            T_Ocean          T_LandOcean      
##  Min.   :1950   Min.   : 1.00   Min.   :1950   Min.   :-1.39426   Min.   :-0.53360   Min.   :-0.70738  
##  1st Qu.:1968   1st Qu.: 3.75   1st Qu.:1968   1st Qu.:-0.26548   1st Qu.:-0.23703   1st Qu.:-0.24216  
##  Median :1986   Median : 6.50   Median :1987   Median : 0.07416   Median :-0.03541   Median :-0.00748  
##  Mean   :1986   Mean   : 6.50   Mean   :1987   Mean   : 0.18632   Mean   :-0.02702   Mean   : 0.03909  
##  3rd Qu.:2005   3rd Qu.: 9.25   3rd Qu.:2005   3rd Qu.: 0.64032   3rd Qu.: 0.15708   3rd Qu.: 0.31314  
##  Max.   :2023   Max.   :12.00   Max.   :2024   Max.   : 2.26227   Max.   : 0.72358   Max.   : 1.18047  
##                                                                                                        
##    ONI_total        ONI_anm           ONI_code            CO2_mean       CO2_deseas   
##  Min.   :24.38   Min.   :-2.03000   Length:888         Min.   :312.4   Min.   :314.4  
##  1st Qu.:26.23   1st Qu.:-0.57000   Class :character   1st Qu.:330.2   1st Qu.:330.5  
##  Median :26.95   Median :-0.05000   Mode  :character   Median :354.9   Median :355.2  
##  Mean   :26.90   Mean   : 0.00911                      Mean   :358.7   Mean   :358.7  
##  3rd Qu.:27.54   3rd Qu.: 0.53000                      3rd Qu.:384.2   3rd Qu.:384.0  
##  Max.   :29.26   Max.   : 2.64000                      Max.   :424.0   Max.   :422.6  
##                                                        NA&#39;s   :98      NA&#39;s   :98     
##  CO2_local_anm     
##  Min.   :-3.62000  
##  1st Qu.:-1.90000  
##  Median : 0.32000  
##  Mean   : 0.00016  
##  3rd Qu.: 2.00250  
##  Max.   : 3.52000  
##  NA&#39;s   :98</code></pre>
<p>Note the missing CO<sub>2</sub> data prior to 1958.</p>
<p>Decode the ONI_code variable, a character on input, in to a factor
and order the factors from “La Niña” to “El Niño” (with “Neutral” in the
middle.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" tabindex="-1"></a><span class="co"># recode ONI_code as a factor</span></span>
<span id="cb29-2"><a href="#cb29-2" tabindex="-1"></a>NOAA<span class="sc">$</span>ONI_code <span class="ot">&lt;-</span> <span class="fu">factor</span>(NOAA<span class="sc">$</span>ONI_code, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;La Niña&quot;</span>, <span class="st">&quot;Neutral&quot;</span>, <span class="st">&quot;El Niño&quot;</span>))</span></code></pre></div>
<p>Get a simple plot:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a><span class="co"># plots</span></span>
<span id="cb30-2"><a href="#cb30-2" tabindex="-1"></a><span class="fu">plot</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;gray70&quot;</span>, <span class="at">lwd =</span> <span class="fl">1.5</span>, <span class="at">data =</span> NOAA)</span>
<span id="cb30-3"><a href="#cb30-3" tabindex="-1"></a><span class="fu">points</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span><span class="fl">0.8</span>, <span class="at">data =</span> NOAA)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-13-1.png" width="2100" /></p>
<p>Here’s a <code>{gglot2}</code> version of the basic plot:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" tabindex="-1"></a><span class="co"># ggplot2 version</span></span>
<span id="cb31-2"><a href="#cb31-2" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> NOAA, <span class="fu">aes</span>(<span class="at">x=</span>YrMn, <span class="at">y=</span>T_LandOcean)) <span class="sc">+</span> </span>
<span id="cb31-3"><a href="#cb31-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb31-5"><a href="#cb31-5" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">1950</span>, <span class="dv">2025</span>, <span class="at">by =</span> <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">1.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.25</span>),</span>
<span id="cb31-7"><a href="#cb31-7" tabindex="-1"></a>                     <span class="at">minor_breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">&quot;NOAA Global Average Temperature Anomalies (&quot;</span>,<span class="st">&quot;°&quot;</span>,<span class="st">&quot;C)&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;&quot;</span>), </span>
<span id="cb31-9"><a href="#cb31-9" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Land + Ocean&quot;</span>) <span class="sc">+</span> </span>
<span id="cb31-10"><a href="#cb31-10" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-14-1.png" width="2100" /></p>
<p>Even at this point, there’s some visual evidence that the
relationship is curvilinear, with the slope of the trend increasing over
time. We’ll postpone dealing with that for a little while.</p>
<p>For later use, create another data frame, removing the observations
with missing CO<sub>2</sub> data.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a><span class="co"># remove records with missing CO2</span></span>
<span id="cb32-2"><a href="#cb32-2" tabindex="-1"></a>NOAA2 <span class="ot">&lt;-</span> NOAA[<span class="sc">!</span><span class="fu">is.na</span>(NOAA[, <span class="dv">10</span>]), ]</span>
<span id="cb32-3"><a href="#cb32-3" tabindex="-1"></a><span class="fu">summary</span>(NOAA2)</span></code></pre></div>
<pre><code>##       Year          Month             YrMn          T_Land           T_Ocean           T_LandOcean      
##  Min.   :1958   Min.   : 1.000   Min.   :1958   Min.   :-1.3943   Min.   :-0.533599   Min.   :-0.60830  
##  1st Qu.:1974   1st Qu.: 4.000   1st Qu.:1975   1st Qu.:-0.2130   1st Qu.:-0.183695   1st Qu.:-0.20462  
##  Median :1991   Median : 7.000   Median :1991   Median : 0.1742   Median :-0.004275   Median : 0.04485  
##  Mean   :1991   Mean   : 6.513   Mean   :1991   Mean   : 0.2520   Mean   : 0.010756   Mean   : 0.08551  
##  3rd Qu.:2007   3rd Qu.: 9.750   3rd Qu.:2007   3rd Qu.: 0.7062   3rd Qu.: 0.178960   3rd Qu.: 0.34230  
##  Max.   :2023   Max.   :12.000   Max.   :2024   Max.   : 2.2623   Max.   : 0.723581   Max.   : 1.18047  
##    ONI_total        ONI_anm            ONI_code      CO2_mean       CO2_deseas    CO2_local_anm      
##  Min.   :24.38   Min.   :-2.03000   La Niña:216   Min.   :312.4   Min.   :314.4   Min.   :-3.620000  
##  1st Qu.:26.28   1st Qu.:-0.55750   Neutral:367   1st Qu.:330.2   1st Qu.:330.5   1st Qu.:-1.900000  
##  Median :26.99   Median :-0.04500   El Niño:207   Median :354.9   Median :355.2   Median : 0.320000  
##  Mean   :26.94   Mean   : 0.01356                 Mean   :358.7   Mean   :358.7   Mean   : 0.000165  
##  3rd Qu.:27.57   3rd Qu.: 0.51000                 3rd Qu.:384.2   3rd Qu.:384.0   3rd Qu.: 2.002500  
##  Max.   :29.26   Max.   : 2.64000                 Max.   :424.0   Max.   :422.6   Max.   : 3.520000</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" tabindex="-1"></a><span class="fu">str</span>(NOAA2)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    790 obs. of  12 variables:
##  $ Year         : int  1958 1958 1958 1958 1958 1958 1958 1958 1958 1958 ...
##  $ Month        : int  3 4 5 6 7 8 9 10 11 12 ...
##  $ YrMn         : num  1958 1958 1958 1958 1958 ...
##  $ T_Land       : num  -0.458 -0.513 -0.192 -0.715 -0.422 ...
##  $ T_Ocean      : num  -0.145 -0.169 -0.239 -0.182 -0.209 ...
##  $ T_LandOcean  : num  -0.242 -0.276 -0.224 -0.347 -0.275 ...
##  $ ONI_total    : num  28.3 28.3 28.2 27.9 27.4 ...
##  $ ONI_anm      : num  1.27 0.93 0.74 0.64 0.57 0.43 0.39 0.44 0.5 0.61 ...
##  $ ONI_code     : Factor w/ 3 levels &quot;La Niña&quot;,&quot;Neutral&quot;,..: 3 3 3 3 3 2 2 2 3 3 ...
##  $ CO2_mean     : num  316 317 318 317 316 ...
##  $ CO2_deseas   : num  314 315 315 315 315 ...
##  $ CO2_local_anm: num  1.27 2.29 2.8 2.1 0.68 -1.25 -2.88 -2.98 -1.87 -0.76 ...</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" tabindex="-1"></a><span class="fu">head</span>(NOAA2)</span></code></pre></div>
<pre><code>##     Year Month     YrMn    T_Land   T_Ocean T_LandOcean ONI_total ONI_anm ONI_code CO2_mean CO2_deseas
## 99  1958     3 1958.167 -0.458099 -0.144789   -0.241868     28.26    1.27  El Niño   315.70     314.43
## 100 1958     4 1958.250 -0.512921 -0.169475   -0.275892     28.28    0.93  El Niño   317.45     315.16
## 101 1958     5 1958.333 -0.191902 -0.238545   -0.224092     28.19    0.74  El Niño   317.51     314.71
## 102 1958     6 1958.417 -0.715345 -0.182276   -0.347448     27.87    0.64  El Niño   317.24     315.14
## 103 1958     7 1958.500 -0.422489 -0.208782   -0.274998     27.38    0.57  El Niño   315.86     315.18
## 104 1958     8 1958.583 -0.471543 -0.189235   -0.276708     26.85    0.43  Neutral   314.93     316.18
##     CO2_local_anm
## 99           1.27
## 100          2.29
## 101          2.80
## 102          2.10
## 103          0.68
## 104         -1.25</code></pre>
<p><a href="regression2.html">[Back to top]</a></p>
</div>
<div id="simple-linear-regression-lm_01" class="section level2"
number="4.2">
<h2><span class="header-section-number">4.2</span> Simple linear
regression (lm_01)</h2>
<p>First, do a simple linear regression with <code>YrMn</code> as the
predictor and land plus ocean temperatures <code>T_LandOcean</code> as
the response.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" tabindex="-1"></a><span class="co"># simple linear (OLS) regression line</span></span>
<span id="cb38-2"><a href="#cb38-2" tabindex="-1"></a>lm_01 <span class="ot">&lt;-</span> <span class="fu">lm</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA)</span>
<span id="cb38-3"><a href="#cb38-3" tabindex="-1"></a><span class="fu">summary</span>(lm_01)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = T_LandOcean ~ YrMn, data = NOAA)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.42443 -0.10765 -0.00597  0.09488  0.58830 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -2.976e+01  4.793e-01  -62.09   &lt;2e-16 ***
## YrMn         1.500e-02  2.412e-04   62.18   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1536 on 886 degrees of freedom
## Multiple R-squared:  0.8135, Adjusted R-squared:  0.8133 
## F-statistic:  3866 on 1 and 886 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" tabindex="-1"></a><span class="fu">AIC</span>(lm_01)</span></code></pre></div>
<pre><code>## [1] -803.5893</code></pre>
<p>The fit of the “curve” (a straight line in this instance) is pretty
good: the <em>R<sup>2</sup></em> value is 0.8135, which is almost
identical to the adjusted <em>R<sup>2</sup></em>, which also
incorporates the automatic increase in <em>R<sup>2</sup></em> that
occurs as more predictors are added. The Akaike Information Criterion
(AIC) (-803.5893 here( is a similar statistic that trades off the
goodness of fit again the number of parameters that have to be
estimated. In practice we would choose the model with the lowest AIC
value among choices. The <em>t</em>- and <em>F</em>-statistics are also
significant. These are tests of the null hypothesis that the regression
coefficients are 0.0, and that there is a significant relationship
between the response and predictor(s).</p>
<p>Here’s a look at the data, fitted values (the line) and the
residuals, whose sum-of-squares were minimized:</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" tabindex="-1"></a><span class="co"># examine the fitted model -- residuals</span></span>
<span id="cb42-2"><a href="#cb42-2" tabindex="-1"></a><span class="fu">plot</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA, <span class="at">type=</span><span class="st">&quot;n&quot;</span>)</span>
<span id="cb42-3"><a href="#cb42-3" tabindex="-1"></a><span class="fu">abline</span>(lm_01)</span>
<span id="cb42-4"><a href="#cb42-4" tabindex="-1"></a><span class="fu">segments</span>(NOAA<span class="sc">$</span>YrMn, <span class="fu">fitted</span>(lm_01), NOAA<span class="sc">$</span>YrMn, NOAA<span class="sc">$</span>T_LandOcean, <span class="at">col =</span> <span class="st">&quot;gray&quot;</span>)</span>
<span id="cb42-5"><a href="#cb42-5" tabindex="-1"></a><span class="fu">points</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.5</span>)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-17-1.png" width="2100" /></p>
<p>The fitted model can be further examined by looking at the prediction
intervals, which gauge the uncertainty in the predictions from the
model, and the confidence intervals, which gauge the uncertainty in the
regression line.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" tabindex="-1"></a><span class="co"># examine the fitted model -- prediction and confidence limits</span></span>
<span id="cb43-2"><a href="#cb43-2" tabindex="-1"></a><span class="fu">plot</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA, <span class="at">type=</span><span class="st">&quot;n&quot;</span>)</span>
<span id="cb43-3"><a href="#cb43-3" tabindex="-1"></a><span class="fu">abline</span>(lm_01)</span>
<span id="cb43-4"><a href="#cb43-4" tabindex="-1"></a><span class="fu">points</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.5</span>)</span>
<span id="cb43-5"><a href="#cb43-5" tabindex="-1"></a>pred_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">YrMn=</span>NOAA<span class="sc">$</span>YrMn)</span>
<span id="cb43-6"><a href="#cb43-6" tabindex="-1"></a>pred_int <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_01, <span class="at">int=</span><span class="st">&quot;p&quot;</span>, <span class="at">newdata=</span>pred_data)</span>
<span id="cb43-7"><a href="#cb43-7" tabindex="-1"></a>conf_int <span class="ot">&lt;-</span> <span class="fu">predict</span>(lm_01, <span class="at">int=</span><span class="st">&quot;c&quot;</span>, <span class="at">newdata=</span>pred_data)</span>
<span id="cb43-8"><a href="#cb43-8" tabindex="-1"></a><span class="fu">matlines</span>(pred_data<span class="sc">$</span>YrMn, pred_int, <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">2</span>), <span class="at">col=</span><span class="st">&quot;black&quot;</span>)</span>
<span id="cb43-9"><a href="#cb43-9" tabindex="-1"></a><span class="fu">matlines</span>(pred_data<span class="sc">$</span>YrMn, conf_int, <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">2</span>), <span class="at">col=</span><span class="st">&quot;orange&quot;</span>)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-18-1.png" width="2100" /></p>
<p>Close inspection of both intervals shows that the slightly flare out
farther away from the centroid of the data. The fitted line always goes
through the centroid of the data (the mean of the response and the mean
of the predictor), which acts more-or-less as a “pivot” and so it makes
sense that the uncertainties are greater the farther away from that
centroid one goes.</p>
<p>The assumptions can be checked using a few diagnostic plots:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" tabindex="-1"></a><span class="co"># regression diagnostics</span></span>
<span id="cb44-2"><a href="#cb44-2" tabindex="-1"></a>oldpar <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb44-3"><a href="#cb44-3" tabindex="-1"></a><span class="fu">plot</span>(lm_01, <span class="at">which=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>))</span>
<span id="cb44-4"><a href="#cb44-4" tabindex="-1"></a><span class="fu">acf</span>(lm_01<span class="sc">$</span>residuals)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-19-1.png" width="2100" /></p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" tabindex="-1"></a><span class="fu">par</span>(oldpar)</span></code></pre></div>
<p>The residual plot (residuals plotted as a function of the fitted
values) has a distinct inverted arch, suggesting the there is some
non-linearity in the relationship between the response and the predictor
(i.e. a non-linear trend), The <code>qqnorm()</code> plot suggests that
the residuals are essentially normally distributed (except that a few
large residuals are tending to make the upper-tail of the distribution a
little “fat”). Cook’s distance measures the influence of individual
observations on the regression. It’s not unusual in time-series data for
the first and last observations to show greater leverage on the
regression coefficients. The residual autocorrelation function, does,
however, signal that there is considerable autocorrelation in the
residuals. This could arise from incompletely accounting for the trend
in the data, or from short-term persistence in the response. This will
be examined further below.</p>
<div id="eye-balling-the-influence-of-enso-on-the-regression-model"
class="section level3" number="4.2.1">
<h3><span class="header-section-number">4.2.1</span> Eye-balling the
influence of ENSO on the regression model</h3>
<p>The potential influence of ENSO on the trend in the data can be
illustrated by simply labeling the points by the ONI_code values, red
for El Niño, blue for La Niña, and gray for Neutral conditions:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" tabindex="-1"></a><span class="co"># examine the regression equation again, by ENSO state</span></span>
<span id="cb46-2"><a href="#cb46-2" tabindex="-1"></a>pal <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;gray&quot;</span>, <span class="st">&quot;red&quot;</span>)</span>
<span id="cb46-3"><a href="#cb46-3" tabindex="-1"></a><span class="fu">plot</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA, <span class="at">type=</span><span class="st">&quot;n&quot;</span>)</span>
<span id="cb46-4"><a href="#cb46-4" tabindex="-1"></a><span class="fu">abline</span>(lm_01)</span>
<span id="cb46-5"><a href="#cb46-5" tabindex="-1"></a><span class="fu">segments</span>(NOAA<span class="sc">$</span>YrMn, <span class="fu">fitted</span>(lm_01), NOAA<span class="sc">$</span>YrMn, NOAA<span class="sc">$</span>T_LandOcean, <span class="at">col =</span> <span class="st">&quot;gray&quot;</span>)</span>
<span id="cb46-6"><a href="#cb46-6" tabindex="-1"></a><span class="fu">points</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">col =</span> pal[ONI_code])</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-20-1.png" width="2100" /></p>
<p>It’s easy to see that many positive residuals are red, and that many
negative residuals are blue, suggesting that the regression line under
predicts during El Niño conditions and over predicts during La Niña
conditions.</p>
<p>Here’s a <code>{ggplot2}</code> package version of the labeled
plot:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" tabindex="-1"></a><span class="co"># points colored by ENSO state</span></span>
<span id="cb47-2"><a href="#cb47-2" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb47-3"><a href="#cb47-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> NOAA, <span class="fu">aes</span>(<span class="at">x =</span> YrMn, <span class="at">y =</span> T_LandOcean)) <span class="sc">+</span></span>
<span id="cb47-4"><a href="#cb47-4" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> lm_01<span class="sc">$</span>coefficients[<span class="dv">1</span>], <span class="at">slope =</span> lm_01<span class="sc">$</span>coefficients[<span class="dv">2</span>], <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb47-5"><a href="#cb47-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> NOAA, <span class="fu">aes</span>(<span class="at">x =</span> YrMn, <span class="at">y =</span> T_LandOcean, <span class="at">color =</span> ONI_code), <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span> </span>
<span id="cb47-6"><a href="#cb47-6" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> NOAA, <span class="fu">aes</span>(<span class="at">x =</span> YrMn, <span class="at">y =</span> T_LandOcean), <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb47-7"><a href="#cb47-7" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;gray&quot;</span>, <span class="st">&quot;red&quot;</span>),</span>
<span id="cb47-8"><a href="#cb47-8" tabindex="-1"></a>                     <span class="at">limits =</span> <span class="fu">c</span>(<span class="st">&quot;La Niña&quot;</span>, <span class="st">&quot;Neutral&quot;</span>, <span class="st">&quot;El Niño&quot;</span>)) <span class="sc">+</span></span>
<span id="cb47-9"><a href="#cb47-9" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">1950</span>, <span class="dv">2025</span>, <span class="at">by =</span> <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb47-10"><a href="#cb47-10" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">1.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.25</span>), </span>
<span id="cb47-11"><a href="#cb47-11" tabindex="-1"></a>                     <span class="at">minor_breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb47-12"><a href="#cb47-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">&quot;NOAA Global Average Temperature Anomalies (&quot;</span>,<span class="st">&quot;°&quot;</span>,<span class="st">&quot;C)&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;&quot;</span>), </span>
<span id="cb47-13"><a href="#cb47-13" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Land + Ocean&quot;</span>) <span class="sc">+</span> </span>
<span id="cb47-14"><a href="#cb47-14" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span> <span class="fu">guide_legend</span>(<span class="at">override.aes =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="dv">3</span>))) <span class="sc">+</span></span>
<span id="cb47-15"><a href="#cb47-15" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-21-1.png" width="2100" /></p>
<p>Here’s a plot of the residuals, on the same scales as the data
plot:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" tabindex="-1"></a><span class="co"># residuals</span></span>
<span id="cb48-2"><a href="#cb48-2" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb48-3"><a href="#cb48-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> NOAA, <span class="fu">aes</span>(<span class="at">x =</span> YrMn, <span class="at">y =</span> <span class="fu">residuals</span>(lm_01))) <span class="sc">+</span></span>
<span id="cb48-4"><a href="#cb48-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> NOAA, <span class="fu">aes</span>(<span class="at">x =</span> YrMn, <span class="at">y =</span> <span class="fu">residuals</span>(lm_01), <span class="at">color =</span> ONI_code), <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span> </span>
<span id="cb48-5"><a href="#cb48-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> NOAA, <span class="fu">aes</span>(<span class="at">x =</span> YrMn, <span class="at">y =</span> <span class="fu">residuals</span>(lm_01)), <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb48-6"><a href="#cb48-6" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;gray&quot;</span>, <span class="st">&quot;red&quot;</span>),</span>
<span id="cb48-7"><a href="#cb48-7" tabindex="-1"></a>                     <span class="at">limits =</span> <span class="fu">c</span>(<span class="st">&quot;La Niña&quot;</span>, <span class="st">&quot;Neutral&quot;</span>, <span class="st">&quot;El Niño&quot;</span>)) <span class="sc">+</span></span>
<span id="cb48-8"><a href="#cb48-8" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">1950</span>, <span class="dv">2025</span>, <span class="at">by =</span> <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb48-9"><a href="#cb48-9" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">1.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.25</span>)</span>
<span id="cb48-10"><a href="#cb48-10" tabindex="-1"></a>                     , <span class="at">minor_breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb48-11"><a href="#cb48-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">&quot;NOAA Global Average Temperature Anomalies (&quot;</span>,<span class="st">&quot;°&quot;</span>,<span class="st">&quot;C)&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;&quot;</span>), </span>
<span id="cb48-12"><a href="#cb48-12" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Land + Ocean (Residuals)&quot;</span>) <span class="sc">+</span> </span>
<span id="cb48-13"><a href="#cb48-13" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span> <span class="fu">guide_legend</span>(<span class="at">override.aes =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="dv">3</span>))) <span class="sc">+</span></span>
<span id="cb48-14"><a href="#cb48-14" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-22-1.png" width="2100" /></p>
<p>The plot of the residuals from the first model versus time again
hints and some non-linearity in the trend and the sorting of the
residual values by ENSO state is quite evident. To look at this further,
we can use a grouped box plot:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" tabindex="-1"></a><span class="co"># residual grouped box plot</span></span>
<span id="cb49-2"><a href="#cb49-2" tabindex="-1"></a>opar <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb49-3"><a href="#cb49-3" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">residuals</span>(lm_01) <span class="sc">~</span> NOAA<span class="sc">$</span>ONI_code, <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb49-4"><a href="#cb49-4" tabindex="-1"></a><span class="fu">par</span>(opar)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-23-1.png" width="2100" /></p>
<p>From the box plots, it’s possible to infer that the median of the
residuals during El Niño conditions is about 0.1 <sup>o</sup>C higher
than during La Niña” conditions, while the median during Neutral
conditions is very close to 0.0.</p>
<p>The assumptions that underlie ordinary least-squares regression
essentially state that there should be no discernible pattern in the
residuals, apart from being normally distributed random numbers. When
that assumption is satisfied, then the Gauss-Markov theorem assures us
that there is no better way to estimate the regression coefficients.
Here, however, there are clear patterns in the residuals: they have a
slight curvilinear trend, are autocorrelated, but mainly show
considerable bias related to ENSO state.</p>
<p><a href="regression2.html">[Back to top]</a></p>
</div>
</div>
<div id="dummy-variable-regression-lm_02" class="section level2"
number="4.3">
<h2><span class="header-section-number">4.3</span> Dummy-variable
regression (lm_02)</h2>
<p>One approach for easily learning about the consequences of a “group
membership” variable like ENSO state as represented by the
<code>ONI_code</code> is the unfortunately named “dummy variable
regression.” The name arises from the generation of various “dummy” (or
indicator) variables, that can be employed to estimate separate
intercept and slope values for the different groups. For example, a set
of variables for examining the variations in intercepts across groups
would take on the value 0.0, except when the particular ENSO state
occurs, when it would be set equal to 1.0, and likewise, to examine
variations in slope the dummy variables would set equal to 0.0, except
when the particular ENSO state occurs, when it would be set equal to the
predictor variable, in this case <code>YrMn</code>. Although the dummy
variables could be generated for all three ENSO states (in this
example), only two of each kind would be included in what’s now a
multiple regression model because including all three would lead to
linearities among predictors: the sum of the intercept-estimating dummy
variables would equal 1.0 for every observation, while the sum of the
slope-estimating variables would equal <code>YrMn</code>.</p>
<p>In the current example, we’ll include the dummy variables for Neutral
and El Niño conditions (omitting those for La Niña conditions). To
interpret the results, the intercept and slope for La Niña conditions
would simply be the overall intercept and slope of the fitted model. The
intercept for El Niño conditions would be the sum of the overall
intercept and the coefficient of the El Niño-condition (0 or 1)
intercept dummy variable, while the slope for El Niño conditions would
be the sum of the overall slope and the coefficient of the El Niño
condition (0 or <code>YrMn</code>) slope dummy variable. Dummy-variable
regression is much more elegant than its name implies.</p>
<p>It turns out that the “equation” language in R takes care of the
generation of the dummy variables (and leaving one out). (But there will
be an example of explicit generation of dummy variables below.) Here’s
the code to look at only the difference in intercept among ENSO-state
groups.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" tabindex="-1"></a><span class="co"># dummy-variable regression</span></span>
<span id="cb50-2"><a href="#cb50-2" tabindex="-1"></a>lm_02 <span class="ot">&lt;-</span> <span class="fu">lm</span>(T_LandOcean <span class="sc">~</span> YrMn <span class="sc">+</span> ONI_code, <span class="at">data =</span> NOAA)</span>
<span id="cb50-3"><a href="#cb50-3" tabindex="-1"></a><span class="fu">summary</span>(lm_02)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = T_LandOcean ~ YrMn + ONI_code, data = NOAA)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.41602 -0.10532 -0.00456  0.09082  0.50530 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     -3.018e+01  4.543e-01 -66.428  &lt; 2e-16 ***
## YrMn             1.518e-02  2.283e-04  66.490  &lt; 2e-16 ***
## ONI_codeNeutral  5.553e-02  1.169e-02   4.749 2.38e-06 ***
## ONI_codeEl Niño  1.386e-01  1.311e-02  10.570  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1447 on 884 degrees of freedom
## Multiple R-squared:  0.8347, Adjusted R-squared:  0.8342 
## F-statistic:  1488 on 3 and 884 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>All of the coefficients in the model are significant as before, and
the <em>R<sup>2</sup></em> value has gone up. One way to gauge the
improvement by the second model over the first is to compare the AIC
values:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" tabindex="-1"></a><span class="co"># print AIC values</span></span>
<span id="cb52-2"><a href="#cb52-2" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(<span class="fu">AIC</span>(lm_01), <span class="fu">AIC</span>(lm_02)))</span></code></pre></div>
<pre><code>## [1] -803.5893 -906.6724</code></pre>
<p>The AIC value for the second model is indeed lower than that for the
first model. Another comparison can be made by doing a simple analysis
of variance:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" tabindex="-1"></a><span class="co"># compare model by ANOVA</span></span>
<span id="cb54-2"><a href="#cb54-2" tabindex="-1"></a><span class="fu">anova</span>(lm_01, lm_02)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: T_LandOcean ~ YrMn
## Model 2: T_LandOcean ~ YrMn + ONI_code
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    886 20.893                                  
## 2    884 18.519  2    2.3734 56.647 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The <em>F</em>-statistic is significant (i.e. it has a low
<em>p</em>-value), and so overall, the second, dummy-variable model
(lm_02) appears to be (statistically) superior to the simple linear
regression model (lm_01).</p>
<p>Here’s what the fitted model looks like:</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" tabindex="-1"></a><span class="co"># display the fitted lines</span></span>
<span id="cb56-2"><a href="#cb56-2" tabindex="-1"></a><span class="fu">plot</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA, <span class="at">type=</span><span class="st">&quot;n&quot;</span>)</span>
<span id="cb56-3"><a href="#cb56-3" tabindex="-1"></a><span class="fu">points</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.5</span>)</span>
<span id="cb56-4"><a href="#cb56-4" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;La Niña&quot;</span>, <span class="st">&quot;Neutral&quot;</span>, <span class="st">&quot;El Niño&quot;</span>), <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">cex=</span><span class="dv">1</span>, <span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;gray&quot;</span>,<span class="st">&quot;red&quot;</span>))</span>
<span id="cb56-5"><a href="#cb56-5" tabindex="-1"></a></span>
<span id="cb56-6"><a href="#cb56-6" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(lm_02)[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;La Niña&quot;</span>] <span class="sc">~</span> NOAA<span class="sc">$</span>YrMn[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;La Niña&quot;</span>], <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>)</span>
<span id="cb56-7"><a href="#cb56-7" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(lm_02)[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;Neutral&quot;</span>] <span class="sc">~</span> NOAA<span class="sc">$</span>YrMn[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;Neutral&quot;</span>], <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;gray&quot;</span>)</span>
<span id="cb56-8"><a href="#cb56-8" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(lm_02)[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;El Niño&quot;</span>] <span class="sc">~</span> NOAA<span class="sc">$</span>YrMn[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;El Niño&quot;</span>], <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-27-1.png" width="2100" /></p>
<p>Here is comparison of the grouped box plots for the two models:</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" tabindex="-1"></a><span class="co"># residual grouped box plot</span></span>
<span id="cb57-2"><a href="#cb57-2" tabindex="-1"></a>opar <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb57-3"><a href="#cb57-3" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">residuals</span>(lm_01) <span class="sc">~</span> NOAA<span class="sc">$</span>ONI_code, <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb57-4"><a href="#cb57-4" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">residuals</span>(lm_02) <span class="sc">~</span> NOAA<span class="sc">$</span>ONI_code, <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb57-5"><a href="#cb57-5" tabindex="-1"></a><span class="fu">par</span>(opar)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-28-1.png" width="2100" /></p>
<p>The bias in the residuals (positive for El Niño conditions, negative
for La Niña conditions) has evidently removed.</p>
<p><a href="regression2.html">[Back to top]</a></p>
</div>
<div
id="dummy-variable-regression-both-intercept-and-slope-varying-lm_03"
class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Dummy-variable
regression, both intercept and slope varying (lm_03)</h2>
<p>Here is the code for fitting a model where both intercept and slope
vary. (Note the subtle difference, an <code>*</code> instead of a
<code>+</code> in the model specification.)</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" tabindex="-1"></a><span class="co"># dummy-variable regression, slope and intercept varying</span></span>
<span id="cb58-2"><a href="#cb58-2" tabindex="-1"></a>lm_03 <span class="ot">&lt;-</span> <span class="fu">lm</span>(T_LandOcean <span class="sc">~</span> YrMn <span class="sc">*</span> ONI_code, <span class="at">data =</span> NOAA)</span>
<span id="cb58-3"><a href="#cb58-3" tabindex="-1"></a><span class="fu">summary</span>(lm_03)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = T_LandOcean ~ YrMn * ONI_code, data = NOAA)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.41236 -0.10266 -0.00416  0.09006  0.50897 
## 
## Coefficients:
##                        Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          -3.156e+01  8.153e-01 -38.712   &lt;2e-16 ***
## YrMn                  1.587e-02  4.097e-04  38.741   &lt;2e-16 ***
## ONI_codeNeutral       2.337e+00  1.075e+00   2.174   0.0300 *  
## ONI_codeEl Niño       1.711e+00  1.189e+00   1.439   0.1505    
## YrMn:ONI_codeNeutral -1.148e-03  5.407e-04  -2.122   0.0341 *  
## YrMn:ONI_codeEl Niño -7.903e-04  5.982e-04  -1.321   0.1868    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1445 on 882 degrees of freedom
## Multiple R-squared:  0.8356, Adjusted R-squared:  0.8346 
## F-statistic: 896.5 on 5 and 882 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Compare the models:</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" tabindex="-1"></a><span class="co"># print AIC values</span></span>
<span id="cb60-2"><a href="#cb60-2" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(<span class="fu">AIC</span>(lm_01), <span class="fu">AIC</span>(lm_02), <span class="fu">AIC</span>(lm_03)))</span></code></pre></div>
<pre><code>## [1] -803.5893 -906.6724 -907.2618</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" tabindex="-1"></a><span class="co"># compare via ANOVA</span></span>
<span id="cb62-2"><a href="#cb62-2" tabindex="-1"></a><span class="fu">anova</span>(lm_02, lm_03)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: T_LandOcean ~ YrMn + ONI_code
## Model 2: T_LandOcean ~ YrMn * ONI_code
##   Res.Df    RSS Df Sum of Sq      F Pr(&gt;F)
## 1    884 18.519                           
## 2    882 18.424  2  0.095464 2.2851 0.1024</code></pre>
<p>The AIC value for this third (intercept + slope varying model) is a
little lower than for the second, but the analysis of variance suggest
there’s not much difference in the explained variance. (Small
<em>F</em>-statistic, large “p*-value.)</p>
<p>The fitted lines show little variation:</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" tabindex="-1"></a><span class="co"># display the fitted lines</span></span>
<span id="cb64-2"><a href="#cb64-2" tabindex="-1"></a><span class="fu">plot</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA, <span class="at">type=</span><span class="st">&quot;n&quot;</span>)</span>
<span id="cb64-3"><a href="#cb64-3" tabindex="-1"></a><span class="fu">points</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.5</span>)</span>
<span id="cb64-4"><a href="#cb64-4" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;La Niña&quot;</span>, <span class="st">&quot;Neutral&quot;</span>, <span class="st">&quot;El Niño&quot;</span>), <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">cex=</span><span class="dv">1</span>, <span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;gray&quot;</span>,<span class="st">&quot;red&quot;</span>))</span>
<span id="cb64-5"><a href="#cb64-5" tabindex="-1"></a></span>
<span id="cb64-6"><a href="#cb64-6" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(lm_03)[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;La Niña&quot;</span>] <span class="sc">~</span> NOAA<span class="sc">$</span>YrMn[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;La Niña&quot;</span>], <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>)</span>
<span id="cb64-7"><a href="#cb64-7" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(lm_03)[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;Neutral&quot;</span>] <span class="sc">~</span> NOAA<span class="sc">$</span>YrMn[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;Neutral&quot;</span>], <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;gray&quot;</span>)</span>
<span id="cb64-8"><a href="#cb64-8" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(lm_03)[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;El Niño&quot;</span>] <span class="sc">~</span> NOAA<span class="sc">$</span>YrMn[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;El Niño&quot;</span>], <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-32-1.png" width="2100" /></p>
<p>The slope for the Neutral conditions is a little lower than for the
La Niña and El Niño, which doesn’t have an immediately apparent physical
explanation.</p>
<p>Here is the same plot, with the regression lines for
<code>lm_02</code> added as dashed lines:</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" tabindex="-1"></a><span class="co"># display the fitted lines</span></span>
<span id="cb65-2"><a href="#cb65-2" tabindex="-1"></a><span class="fu">plot</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA, <span class="at">type=</span><span class="st">&quot;n&quot;</span>)</span>
<span id="cb65-3"><a href="#cb65-3" tabindex="-1"></a><span class="fu">points</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.5</span>)</span>
<span id="cb65-4"><a href="#cb65-4" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;La Niña&quot;</span>, <span class="st">&quot;Neutral&quot;</span>, <span class="st">&quot;El Niño&quot;</span>), <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">cex=</span><span class="dv">1</span>, <span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;gray&quot;</span>,<span class="st">&quot;red&quot;</span>))</span>
<span id="cb65-5"><a href="#cb65-5" tabindex="-1"></a></span>
<span id="cb65-6"><a href="#cb65-6" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(lm_03)[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;La Niña&quot;</span>] <span class="sc">~</span> NOAA<span class="sc">$</span>YrMn[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;La Niña&quot;</span>], <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>)</span>
<span id="cb65-7"><a href="#cb65-7" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(lm_03)[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;Neutral&quot;</span>] <span class="sc">~</span> NOAA<span class="sc">$</span>YrMn[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;Neutral&quot;</span>], <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;gray&quot;</span>)</span>
<span id="cb65-8"><a href="#cb65-8" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(lm_03)[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;El Niño&quot;</span>] <span class="sc">~</span> NOAA<span class="sc">$</span>YrMn[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;El Niño&quot;</span>], <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span>
<span id="cb65-9"><a href="#cb65-9" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(lm_02)[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;La Niña&quot;</span>] <span class="sc">~</span> NOAA<span class="sc">$</span>YrMn[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;La Niña&quot;</span>], <span class="at">lwd=</span><span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>)</span>
<span id="cb65-10"><a href="#cb65-10" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(lm_02)[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;Neutral&quot;</span>] <span class="sc">~</span> NOAA<span class="sc">$</span>YrMn[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;Neutral&quot;</span>], <span class="at">lwd=</span><span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>,<span class="at">col=</span><span class="st">&quot;black&quot;</span>)</span>
<span id="cb65-11"><a href="#cb65-11" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(lm_02)[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;El Niño&quot;</span>] <span class="sc">~</span> NOAA<span class="sc">$</span>YrMn[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;El Niño&quot;</span>], <span class="at">lwd=</span><span class="dv">1</span>, <span class="at">lty =</span> <span class="dv">2</span>,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-33-1.png" width="2100" /></p>
<p>With negligible improvement in the goodness of fit of
<code>lm_03</code>, and no practical differences in the curves, there
seems to be little reason to declare the model where both intercept and
slope vary among ENSO states as any better than the one where just the
intercept varies. In fact the “principle of parsimony” in statistics
would strongly argue for <code>lm_02</code> as the better model.</p>
<p><a href="regression2.html">[Back to top]</a></p>
</div>
</div>
<div id="a-model-with-co2-as-the-predictor-variable"
class="section level1" number="5">
<h1><span class="header-section-number">5</span> A model with
CO<sub>2</sub> as the predictor variable</h1>
<p>Although it makes sense when trying to assess the overall trend in
global temperatures to use time (<code>YrMn</code>) as a predictor, we
know that in fact, it’s the level of CO<sub>2</sub> and other greenhouse
gasses (GHGs) that are responsible for the temperature increase. The
NOAA data set from Mauna Loa contains both the mean monthly values of
CO<sub>2</sub> (plotted in red below) and a “deseasonalized” value (that
takes out the prominent annual cycle in the CO<sub>2</sub> data related
to the “respiration” of the Northern Hemisphere biosphere, plotted in
black.) There is some spatial variability inn monthly CO<sub>2</sub>
values, with the Northern and Southern Hemispheres being “antiphased”,
and so for looking at global temperatures, it makes the most sense to
use the deseasonalized values as a potential predictor.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" tabindex="-1"></a><span class="fu">plot</span>(CO2_mean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA2, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">cex =</span> <span class="fl">0.3</span>, <span class="at">ylab =</span> <span class="fu">expression</span>(<span class="st">&quot;Mauna Loa CO&quot;</span>[<span class="dv">2</span>]))</span>
<span id="cb66-2"><a href="#cb66-2" tabindex="-1"></a><span class="fu">points</span>(CO2_deseas <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA2, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">col =</span> <span class="st">&quot;black&quot;</span>, <span class="at">cex =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-34-1.png" width="2100" /></p>
<div id="simple-linear-regression-co2-as-a-predictor-lm_05"
class="section level2" number="5.1">
<h2><span class="header-section-number">5.1</span> Simple linear
regression, CO<sub>2</sub> as a predictor (lm_05)</h2>
<p>For comparison, using now the <code>NOAA2</code> data frame, in which
the earlier months when CO<sub>2</sub> data were not yet available, the
simple linear model with <code>YrMn</code> as a predictor is:</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" tabindex="-1"></a><span class="co"># simple linear (OLS) regression line, only with NOAA2</span></span>
<span id="cb67-2"><a href="#cb67-2" tabindex="-1"></a>lm_04 <span class="ot">&lt;-</span> <span class="fu">lm</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA2)</span>
<span id="cb67-3"><a href="#cb67-3" tabindex="-1"></a><span class="fu">summary</span>(lm_04)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = T_LandOcean ~ YrMn, data = NOAA2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.41121 -0.09806 -0.00504  0.08744  0.55267 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -3.284e+01  5.352e-01  -61.36   &lt;2e-16 ***
## YrMn         1.654e-02  2.688e-04   61.52   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1436 on 788 degrees of freedom
## Multiple R-squared:  0.8277, Adjusted R-squared:  0.8275 
## F-statistic:  3785 on 1 and 788 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" tabindex="-1"></a><span class="fu">AIC</span>(lm_04)</span></code></pre></div>
<pre><code>## [1] -820.6057</code></pre>
<p>Now here is the model with CO<sub>2</sub> as the predictor:</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" tabindex="-1"></a><span class="co"># simple linear (OLS) regression line, CO2 as predictor</span></span>
<span id="cb71-2"><a href="#cb71-2" tabindex="-1"></a>lm_05 <span class="ot">&lt;-</span> <span class="fu">lm</span>(T_LandOcean <span class="sc">~</span> CO2_deseas, <span class="at">data =</span> NOAA2)</span>
<span id="cb71-3"><a href="#cb71-3" tabindex="-1"></a><span class="fu">summary</span>(lm_05)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = T_LandOcean ~ CO2_deseas, data = NOAA2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.38251 -0.08850 -0.00339  0.08606  0.45234 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -3.5787293  0.0538327  -66.48   &lt;2e-16 ***
## CO2_deseas   0.0102153  0.0001495   68.33   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1314 on 788 degrees of freedom
## Multiple R-squared:  0.8556, Adjusted R-squared:  0.8554 
## F-statistic:  4668 on 1 and 788 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" tabindex="-1"></a><span class="fu">AIC</span>(lm_05)</span></code></pre></div>
<pre><code>## [1] -960.1603</code></pre>
<p>Here are the residual diagnostic plots:</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" tabindex="-1"></a><span class="co"># regression diagnostics</span></span>
<span id="cb75-2"><a href="#cb75-2" tabindex="-1"></a>oldpar <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb75-3"><a href="#cb75-3" tabindex="-1"></a><span class="fu">plot</span>(lm_05, <span class="at">which=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>))</span>
<span id="cb75-4"><a href="#cb75-4" tabindex="-1"></a><span class="fu">acf</span>(<span class="fu">residuals</span>(lm_05))</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-37-1.png" width="2100" /></p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" tabindex="-1"></a><span class="fu">par</span>(oldpar)</span></code></pre></div>
<p>In general, except for autocorrelation of the residuals, the
residuals are a bit better behaved relative to the first model
<code>lm_01</code>. The <em>R<sup>2</sup></em>-squared values are
higher, and the AIC more negative for the model with CO<sub>2</sub> as a
predictor, suggesting that overall it’s a better predictor of the trend
in monthly global-averaged temperatures than simply time. (Not
surprising)</p>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(<span class="fu">AIC</span>(lm_04), <span class="fu">AIC</span>(lm_05)))</span></code></pre></div>
<pre><code>## [1] -820.6057 -960.1603</code></pre>
<p>Here’s a plot:</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" tabindex="-1"></a><span class="co"># points colored by ENSO state</span></span>
<span id="cb79-2"><a href="#cb79-2" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb79-3"><a href="#cb79-3" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> lm_05<span class="sc">$</span>coeff[<span class="dv">1</span>], <span class="at">slope =</span> lm_05<span class="sc">$</span>coeff[<span class="dv">2</span>], <span class="at">color =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb79-4"><a href="#cb79-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> NOAA2, <span class="fu">aes</span>(<span class="at">x =</span> CO2_deseas, <span class="at">y =</span> T_LandOcean, <span class="at">color =</span> ONI_code), <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb79-5"><a href="#cb79-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> NOAA2, <span class="fu">aes</span>(<span class="at">x =</span> CO2_deseas, <span class="at">y =</span> T_LandOcean), <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb79-6"><a href="#cb79-6" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;gray&quot;</span>, <span class="st">&quot;red&quot;</span>),</span>
<span id="cb79-7"><a href="#cb79-7" tabindex="-1"></a>                     <span class="at">limits =</span> <span class="fu">c</span>(<span class="st">&quot;La Niña&quot;</span>, <span class="st">&quot;Neutral&quot;</span>, <span class="st">&quot;El Niño&quot;</span>)) <span class="sc">+</span></span>
<span id="cb79-8"><a href="#cb79-8" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">315</span>, <span class="dv">430</span>, <span class="at">by =</span> <span class="dv">15</span>)) <span class="sc">+</span></span>
<span id="cb79-9"><a href="#cb79-9" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">1.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.25</span>),</span>
<span id="cb79-10"><a href="#cb79-10" tabindex="-1"></a>                     <span class="at">minor_breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb79-11"><a href="#cb79-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">&quot;NOAA Global Average Temperature Anomalies (&quot;</span>,<span class="st">&quot;°&quot;</span>,<span class="st">&quot;C)&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;&quot;</span>), </span>
<span id="cb79-12"><a href="#cb79-12" tabindex="-1"></a>       <span class="at">x =</span> <span class="fu">expression</span>(CO[<span class="dv">2</span>]<span class="sc">~</span><span class="st">&quot; &quot;</span>(ppm)), <span class="at">y =</span> <span class="st">&quot;Land + Ocean&quot;</span>) <span class="sc">+</span> </span>
<span id="cb79-13"><a href="#cb79-13" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span> <span class="fu">guide_legend</span>(<span class="at">override.aes =</span> <span class="fu">list</span>(<span class="at">size =</span> <span class="dv">3</span>))) <span class="sc">+</span></span>
<span id="cb79-14"><a href="#cb79-14" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-39-1.png" width="2100" /></p>
<p><a href="regression2.html">[Back to top]</a></p>
</div>
<div
id="dummy-variable-regression-intercepts-only-co2-as-a-predictor-lm_06"
class="section level2" number="5.2">
<h2><span class="header-section-number">5.2</span> Dummy-variable
regression, intercepts-only, CO<sub>2</sub> as a predictor (lm_06)</h2>
<p>Next, we’ll fit a dummy-variable regression, with CO<sub>2</sub> as a
predictor, allowing the intercepts to vary among ENSO states:</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" tabindex="-1"></a><span class="co"># dummy-variable regression</span></span>
<span id="cb80-2"><a href="#cb80-2" tabindex="-1"></a>lm_06 <span class="ot">&lt;-</span> <span class="fu">lm</span>(T_LandOcean <span class="sc">~</span> CO2_deseas <span class="sc">+</span> ONI_code, <span class="at">data =</span> NOAA2)</span>
<span id="cb80-3"><a href="#cb80-3" tabindex="-1"></a><span class="fu">summary</span>(lm_06)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = T_LandOcean ~ CO2_deseas + ONI_code, data = NOAA2)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.35895 -0.08403 -0.00315  0.08230  0.37919 
## 
## Coefficients:
##                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)     -3.7102673  0.0522610 -70.995  &lt; 2e-16 ***
## CO2_deseas       0.0103928  0.0001408  73.808  &lt; 2e-16 ***
## ONI_codeNeutral  0.0710392  0.0106123   6.694 4.13e-11 ***
## ONI_codeEl Niño  0.1330918  0.0119674  11.121  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1223 on 786 degrees of freedom
## Multiple R-squared:  0.8753, Adjusted R-squared:  0.8748 
## F-statistic:  1838 on 3 and 786 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(<span class="fu">AIC</span>(lm_05), <span class="fu">AIC</span>(lm_06)))</span></code></pre></div>
<pre><code>## [1]  -960.1603 -1071.8613</code></pre>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" tabindex="-1"></a><span class="fu">anova</span>(lm_05, lm_06)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: T_LandOcean ~ CO2_deseas
## Model 2: T_LandOcean ~ CO2_deseas + ONI_code
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    788 13.615                                  
## 2    786 11.760  2    1.8549 61.986 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>As before, with <code>YrMn</code> as the predictor, the
dummy-variable regression performs better. Here’s a plot”</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" tabindex="-1"></a><span class="co"># display the fitted lines</span></span>
<span id="cb86-2"><a href="#cb86-2" tabindex="-1"></a><span class="fu">plot</span>(T_LandOcean <span class="sc">~</span> CO2_deseas, <span class="at">data =</span> NOAA2, <span class="at">type=</span><span class="st">&quot;n&quot;</span>)</span>
<span id="cb86-3"><a href="#cb86-3" tabindex="-1"></a><span class="fu">points</span>(T_LandOcean <span class="sc">~</span> CO2_deseas, <span class="at">data =</span> NOAA2, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.5</span>)</span>
<span id="cb86-4"><a href="#cb86-4" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">&quot;bottomright&quot;</span>, <span class="at">legend=</span><span class="fu">c</span>(<span class="st">&quot;La Niña&quot;</span>, <span class="st">&quot;Neutral&quot;</span>, <span class="st">&quot;El Niño&quot;</span>), <span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>), <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">cex=</span><span class="dv">1</span>, <span class="at">col=</span><span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>,<span class="st">&quot;gray&quot;</span>,<span class="st">&quot;red&quot;</span>))</span>
<span id="cb86-5"><a href="#cb86-5" tabindex="-1"></a></span>
<span id="cb86-6"><a href="#cb86-6" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(lm_06)[NOAA2<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;La Niña&quot;</span>] <span class="sc">~</span> NOAA2<span class="sc">$</span>CO2_deseas[NOAA2<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;La Niña&quot;</span>], <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;blue&quot;</span>)</span>
<span id="cb86-7"><a href="#cb86-7" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(lm_06)[NOAA2<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;Neutral&quot;</span>] <span class="sc">~</span> NOAA2<span class="sc">$</span>CO2_deseas[NOAA2<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;Neutral&quot;</span>], <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;gray&quot;</span>)</span>
<span id="cb86-8"><a href="#cb86-8" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">fitted</span>(lm_06)[NOAA2<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;El Niño&quot;</span>] <span class="sc">~</span> NOAA2<span class="sc">$</span>CO2_deseas[NOAA2<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;El Niño&quot;</span>], <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-41-1.png" width="2100" /></p>
<p>Here’s the <code>{ggplot2}</code> version:</p>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" tabindex="-1"></a><span class="co"># intercepts and slopes lm_06</span></span>
<span id="cb87-2"><a href="#cb87-2" tabindex="-1"></a>ln_intercept <span class="ot">&lt;-</span> lm_06<span class="sc">$</span>coeff[<span class="dv">1</span>]</span>
<span id="cb87-3"><a href="#cb87-3" tabindex="-1"></a>ln_slope <span class="ot">&lt;-</span> lm_06<span class="sc">$</span>coeff[<span class="dv">2</span>]</span>
<span id="cb87-4"><a href="#cb87-4" tabindex="-1"></a>n_intercept <span class="ot">&lt;-</span> lm_06<span class="sc">$</span>coeff[<span class="dv">1</span>] <span class="sc">+</span> lm_06<span class="sc">$</span>coeff[<span class="dv">3</span>]</span>
<span id="cb87-5"><a href="#cb87-5" tabindex="-1"></a>n_slope <span class="ot">&lt;-</span> lm_06<span class="sc">$</span>coeff[<span class="dv">2</span>] </span>
<span id="cb87-6"><a href="#cb87-6" tabindex="-1"></a>en_intercept <span class="ot">&lt;-</span> lm_06<span class="sc">$</span>coeff[<span class="dv">1</span>] <span class="sc">+</span> lm_06<span class="sc">$</span>coeff[<span class="dv">4</span>]</span>
<span id="cb87-7"><a href="#cb87-7" tabindex="-1"></a>en_slope <span class="ot">&lt;-</span> lm_06<span class="sc">$</span>coeff[<span class="dv">2</span>] </span>
<span id="cb87-8"><a href="#cb87-8" tabindex="-1"></a></span>
<span id="cb87-9"><a href="#cb87-9" tabindex="-1"></a><span class="co"># ggplot2 plot with regression line</span></span>
<span id="cb87-10"><a href="#cb87-10" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> NOAA2, <span class="fu">aes</span>(<span class="at">x =</span> CO2_deseas, <span class="at">y =</span> T_LandOcean)) <span class="sc">+</span> </span>
<span id="cb87-11"><a href="#cb87-11" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> ln_intercept, <span class="at">slope =</span> ln_slope, <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb87-12"><a href="#cb87-12" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> n_intercept, <span class="at">slope =</span> n_slope, <span class="at">color =</span> <span class="st">&quot;gray40&quot;</span>) <span class="sc">+</span></span>
<span id="cb87-13"><a href="#cb87-13" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> en_intercept, <span class="at">slope =</span> en_slope, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb87-14"><a href="#cb87-14" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> NOAA2, <span class="fu">aes</span>(<span class="at">x=</span>CO2_deseas, <span class="at">y=</span>T_LandOcean, <span class="at">color =</span> ONI_code), <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb87-15"><a href="#cb87-15" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> NOAA2, <span class="fu">aes</span>(<span class="at">x=</span>CO2_deseas, <span class="at">y=</span>T_LandOcean), <span class="at">color =</span> <span class="st">&quot;black&quot;</span>,<span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">2</span> ) <span class="sc">+</span></span>
<span id="cb87-16"><a href="#cb87-16" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;gray&quot;</span>, <span class="st">&quot;red&quot;</span>),</span>
<span id="cb87-17"><a href="#cb87-17" tabindex="-1"></a>                     <span class="at">limits =</span> <span class="fu">c</span>(<span class="st">&quot;La Niña&quot;</span>, <span class="st">&quot;Neutral&quot;</span>, <span class="st">&quot;El Niño&quot;</span>)) <span class="sc">+</span> </span>
<span id="cb87-18"><a href="#cb87-18" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">315</span>, <span class="dv">430</span>, <span class="at">by =</span> <span class="dv">15</span>)) <span class="sc">+</span></span>
<span id="cb87-19"><a href="#cb87-19" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">1.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.25</span>), </span>
<span id="cb87-20"><a href="#cb87-20" tabindex="-1"></a>                     <span class="at">minor_breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb87-21"><a href="#cb87-21" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">&quot;NOAA Global Average Temperature Anomalies (&quot;</span>,<span class="st">&quot;°&quot;</span>,<span class="st">&quot;C)&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;&quot;</span>), </span>
<span id="cb87-22"><a href="#cb87-22" tabindex="-1"></a>       <span class="at">x =</span> <span class="fu">expression</span>(CO[<span class="dv">2</span>]<span class="sc">~</span><span class="st">&quot; &quot;</span>(ppm)), <span class="at">y =</span> <span class="st">&quot;Land + Ocean&quot;</span>) <span class="sc">+</span> </span>
<span id="cb87-23"><a href="#cb87-23" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-42-1.png" width="2100" /></p>
<p>The CO<sub>2</sub> have an evident non-linear trend, while the
relationship with temperature seems quite linear. Recalling that there
is a slight tendency in the relationship of temperature with time to be
slightly curvilinear, this suggests global temperatures indeed have a
curvilinear as opposed to linear trend. An interesting addition to a
scatter plot of temperature vs. time, is the fitted values of the
regression with CO<sub>2</sub> as the predictor:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" tabindex="-1"></a><span class="co"># scatter plot with CO2-fitted values ===============================</span></span>
<span id="cb88-2"><a href="#cb88-2" tabindex="-1"></a>ln_fit <span class="ot">&lt;-</span> ln_intercept <span class="sc">+</span> ln_slope<span class="sc">*</span>NOAA2<span class="sc">$</span>CO2_deseas</span>
<span id="cb88-3"><a href="#cb88-3" tabindex="-1"></a>n_fit <span class="ot">&lt;-</span> n_intercept <span class="sc">+</span> n_slope<span class="sc">*</span>NOAA2<span class="sc">$</span>CO2_deseas</span>
<span id="cb88-4"><a href="#cb88-4" tabindex="-1"></a>en_fit <span class="ot">&lt;-</span> en_intercept <span class="sc">+</span> n_slope<span class="sc">*</span>NOAA2<span class="sc">$</span>CO2_deseas</span>
<span id="cb88-5"><a href="#cb88-5" tabindex="-1"></a></span>
<span id="cb88-6"><a href="#cb88-6" tabindex="-1"></a><span class="co"># ggplot2 plot with fitted values line</span></span>
<span id="cb88-7"><a href="#cb88-7" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> NOAA2, <span class="fu">aes</span>(<span class="at">x =</span> YrMn, <span class="at">y =</span> T_LandOcean)) <span class="sc">+</span> </span>
<span id="cb88-8"><a href="#cb88-8" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> NOAA2<span class="sc">$</span>YrMn, <span class="at">y =</span> ln_fit), <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">shape =</span> <span class="dv">4</span>, <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb88-9"><a href="#cb88-9" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> NOAA2<span class="sc">$</span>YrMn, <span class="at">y =</span> n_fit), <span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">shape =</span> <span class="dv">4</span>, <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb88-10"><a href="#cb88-10" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> NOAA2<span class="sc">$</span>YrMn, <span class="at">y =</span> en_fit), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">shape =</span> <span class="dv">4</span>, <span class="at">size =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb88-11"><a href="#cb88-11" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> NOAA2, <span class="fu">aes</span>(<span class="at">x=</span>YrMn, <span class="at">y=</span>T_LandOcean, <span class="at">color =</span> ONI_code), <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb88-12"><a href="#cb88-12" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> NOAA2, <span class="fu">aes</span>(<span class="at">x=</span>YrMn, <span class="at">y=</span>T_LandOcean), <span class="at">color =</span> <span class="st">&quot;black&quot;</span>,<span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">2</span> ) <span class="sc">+</span></span>
<span id="cb88-13"><a href="#cb88-13" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;gray&quot;</span>, <span class="st">&quot;red&quot;</span>),</span>
<span id="cb88-14"><a href="#cb88-14" tabindex="-1"></a>                     <span class="at">limits =</span> <span class="fu">c</span>(<span class="st">&quot;La Niña&quot;</span>, <span class="st">&quot;Neutral&quot;</span>, <span class="st">&quot;El Niño&quot;</span>)) <span class="sc">+</span> </span>
<span id="cb88-15"><a href="#cb88-15" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">1960</span>, <span class="dv">2025</span>, <span class="at">by =</span> <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb88-16"><a href="#cb88-16" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">1.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.25</span>), </span>
<span id="cb88-17"><a href="#cb88-17" tabindex="-1"></a>                     <span class="at">minor_breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb88-18"><a href="#cb88-18" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">&quot;NOAA Global Average Temperature Anomalies (&quot;</span>,<span class="st">&quot;°&quot;</span>,<span class="st">&quot;C)&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;&quot;</span>), </span>
<span id="cb88-19"><a href="#cb88-19" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Land + Ocean&quot;</span>) <span class="sc">+</span> </span>
<span id="cb88-20"><a href="#cb88-20" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-43-1.png" width="2100" /></p>
<p>Above, the fitted or predicted values from <code>lm_06</code> are
plotted as tiny “x”’s, which together give the impression of a
curvilinear relationship.</p>
<p><a href="regression2.html">[Back to top]</a></p>
</div>
</div>
<div id="curvilinear-trends" class="section level1" number="6">
<h1><span class="header-section-number">6</span> Curvilinear trends</h1>
<div id="a-simple-polynomial-trend-lm_07" class="section level2"
number="6.1">
<h2><span class="header-section-number">6.1</span> A simple polynomial
trend (lm_07)</h2>
<p>A curvilinear, second-order polynomial regression model
(i.e. <em>Y<sub>t</sub></em> = <em>b<sub>0</sub></em> +
<em>b<sub>1</sub>X<sub>t</sub></em> +
<em>b<sub>2</sub>X<sub>t</sub><sup>2</sup></em> + e<sub>t</sub>) can be
fit as follows. Note the use of the <code>poly()</code> function to
generate the predictor variables.</p>
<div class="sourceCode" id="cb89"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" tabindex="-1"></a><span class="co"># second-order polynomial</span></span>
<span id="cb89-2"><a href="#cb89-2" tabindex="-1"></a>lm_07 <span class="ot">&lt;-</span> <span class="fu">lm</span>(T_LandOcean <span class="sc">~</span> <span class="fu">poly</span>(YrMn, <span class="dv">2</span>, <span class="at">raw =</span> <span class="cn">TRUE</span>), <span class="at">data =</span> NOAA)</span>
<span id="cb89-3"><a href="#cb89-3" tabindex="-1"></a><span class="fu">summary</span>(lm_07)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = T_LandOcean ~ poly(YrMn, 2, raw = TRUE), data = NOAA)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.37514 -0.09472 -0.00211  0.08680  0.44949 
## 
## Coefficients:
##                              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                 6.656e+02  4.405e+01   15.11   &lt;2e-16 ***
## poly(YrMn, 2, raw = TRUE)1 -6.850e-01  4.435e-02  -15.45   &lt;2e-16 ***
## poly(YrMn, 2, raw = TRUE)2  1.761e-04  1.116e-05   15.79   &lt;2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1357 on 885 degrees of freedom
## Multiple R-squared:  0.8545, Adjusted R-squared:  0.8542 
## F-statistic:  2599 on 2 and 885 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" tabindex="-1"></a><span class="fu">AIC</span>(lm_07)</span></code></pre></div>
<pre><code>## [1] -1021.872</code></pre>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" tabindex="-1"></a><span class="co"># regression diagnostics</span></span>
<span id="cb93-2"><a href="#cb93-2" tabindex="-1"></a>oldpar <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb93-3"><a href="#cb93-3" tabindex="-1"></a><span class="fu">plot</span>(lm_07, <span class="at">which=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>))</span>
<span id="cb93-4"><a href="#cb93-4" tabindex="-1"></a><span class="fu">acf</span>(lm_07<span class="sc">$</span>residuals)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-45-1.png" width="2100" /></p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" tabindex="-1"></a><span class="fu">par</span>(oldpar)</span></code></pre></div>
<p>Note that the AIC value has decreased substantially relative to
<code>lm_04</code> the linear model.</p>
<p>Here is the plot of the polynomial fit:</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" tabindex="-1"></a><span class="co"># examine the regression equation again, by ENSO state</span></span>
<span id="cb95-2"><a href="#cb95-2" tabindex="-1"></a>pal <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;gray&quot;</span>, <span class="st">&quot;red&quot;</span>)</span>
<span id="cb95-3"><a href="#cb95-3" tabindex="-1"></a><span class="fu">plot</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA, <span class="at">type=</span><span class="st">&quot;n&quot;</span>)</span>
<span id="cb95-4"><a href="#cb95-4" tabindex="-1"></a><span class="fu">segments</span>(NOAA<span class="sc">$</span>YrMn, <span class="fu">fitted</span>(lm_07), NOAA<span class="sc">$</span>YrMn, NOAA<span class="sc">$</span>T_LandOcean, <span class="at">col =</span> <span class="st">&quot;gray&quot;</span>)</span>
<span id="cb95-5"><a href="#cb95-5" tabindex="-1"></a><span class="fu">lines</span>(NOAA<span class="sc">$</span>YrMn, <span class="fu">fitted</span>(lm_07))</span>
<span id="cb95-6"><a href="#cb95-6" tabindex="-1"></a><span class="fu">points</span>(T_LandOcean <span class="sc">~</span> YrMn, <span class="at">data =</span> NOAA, <span class="at">pch =</span> <span class="dv">16</span>, <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">col =</span> pal[ONI_code])</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-46-1.png" width="2100" /></p>
<p>The polynomial line seems to better discriminate between the various
ENSO states that the linear regression line did. Here’s a
<code>{ggplot2}</code> with a linear and loess smooth curve added:</p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" tabindex="-1"></a><span class="co"># ggplot2 plot with regression line</span></span>
<span id="cb96-2"><a href="#cb96-2" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> NOAA, <span class="fu">aes</span>(<span class="at">x =</span> YrMn, <span class="at">y =</span> T_LandOcean)) <span class="sc">+</span> </span>
<span id="cb96-3"><a href="#cb96-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;gray70&quot;</span>) <span class="sc">+</span></span>
<span id="cb96-4"><a href="#cb96-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> NOAA, <span class="fu">aes</span>(<span class="at">x =</span> YrMn, <span class="at">y =</span> T_LandOcean, <span class="at">color =</span> ONI_code), <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb96-5"><a href="#cb96-5" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> NOAA, <span class="fu">aes</span>(<span class="at">x =</span> YrMn, <span class="at">y =</span> T_LandOcean), <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb96-6"><a href="#cb96-6" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;gray&quot;</span>, <span class="st">&quot;red&quot;</span>),</span>
<span id="cb96-7"><a href="#cb96-7" tabindex="-1"></a>                     <span class="at">limits =</span> <span class="fu">c</span>(<span class="st">&quot;La Niña&quot;</span>, <span class="st">&quot;Neutral&quot;</span>, <span class="st">&quot;El Niño&quot;</span>)) <span class="sc">+</span></span>
<span id="cb96-8"><a href="#cb96-8" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">level =</span> <span class="fl">0.95</span>) <span class="sc">+</span></span>
<span id="cb96-9"><a href="#cb96-9" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;loess&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">level =</span> <span class="fl">0.95</span>, <span class="at">col =</span> <span class="st">&quot;purple&quot;</span>) <span class="sc">+</span></span>
<span id="cb96-10"><a href="#cb96-10" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> YrMn, <span class="at">y =</span> <span class="fu">fitted</span>(lm_07)), <span class="at">color =</span> <span class="st">&quot;black&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb96-11"><a href="#cb96-11" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">1950</span>, <span class="dv">2025</span>, <span class="at">by =</span> <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb96-12"><a href="#cb96-12" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">1.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.25</span>), </span>
<span id="cb96-13"><a href="#cb96-13" tabindex="-1"></a>                     <span class="at">minor_breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb96-14"><a href="#cb96-14" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">&quot;NOAA Global Average Temperature Anomalies (&quot;</span>,<span class="st">&quot;°&quot;</span>,<span class="st">&quot;C)&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;&quot;</span>), </span>
<span id="cb96-15"><a href="#cb96-15" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Land + Ocean&quot;</span>) <span class="sc">+</span> </span>
<span id="cb96-16"><a href="#cb96-16" tabindex="-1"></a>  <span class="fu">theme_bw</span>() </span></code></pre></div>
<pre><code>## Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
## ℹ Please use `linewidth` instead.
## This warning is displayed once every 8 hours.
## Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated.</code></pre>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;
## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<p><img src="regression2_files/figure-html/regression2-47-1.png" width="2100" />
And the residual grouped box plot shows that, relative to the original
model <code>lm_01</code> the variability of the residuals is smaller,
but they are still biased by ENSO state:</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" tabindex="-1"></a><span class="co"># residual grouped box plot</span></span>
<span id="cb99-2"><a href="#cb99-2" tabindex="-1"></a>opar <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb99-3"><a href="#cb99-3" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">residuals</span>(lm_01) <span class="sc">~</span> NOAA<span class="sc">$</span>ONI_code, <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb99-4"><a href="#cb99-4" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">residuals</span>(lm_07) <span class="sc">~</span> NOAA<span class="sc">$</span>ONI_code, <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb99-5"><a href="#cb99-5" tabindex="-1"></a><span class="fu">par</span>(opar)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-48-1.png" width="2100" /></p>
</div>
<div id="a-polynomial-dummy-variable-regression-lm_08"
class="section level2" number="6.2">
<h2><span class="header-section-number">6.2</span> A polynomial
dummy-variable regression (lm_08)</h2>
<p>The obvious solution to deal with the ENSO-state bias in the
residuals is to again implement a dummy-variable regression. Here’s the
code and results:</p>
<div class="sourceCode" id="cb100"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" tabindex="-1"></a><span class="co"># simple linear (OLS) regression line</span></span>
<span id="cb100-2"><a href="#cb100-2" tabindex="-1"></a>lm_08 <span class="ot">&lt;-</span> <span class="fu">lm</span>(T_LandOcean <span class="sc">~</span> <span class="fu">poly</span>(YrMn, <span class="dv">2</span>, <span class="at">raw =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> ONI_code, <span class="at">data =</span> NOAA)</span>
<span id="cb100-3"><a href="#cb100-3" tabindex="-1"></a><span class="fu">summary</span>(lm_08)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = T_LandOcean ~ poly(YrMn, 2, raw = TRUE) + ONI_code, 
##     data = NOAA)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.35098 -0.08639 -0.00044  0.08542  0.41352 
## 
## Coefficients:
##                              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                 6.840e+02  4.058e+01  16.856  &lt; 2e-16 ***
## poly(YrMn, 2, raw = TRUE)1 -7.038e-01  4.085e-02 -17.229  &lt; 2e-16 ***
## poly(YrMn, 2, raw = TRUE)2  1.809e-04  1.028e-05  17.601  &lt; 2e-16 ***
## ONI_codeNeutral             6.997e-02  1.010e-02   6.928 8.21e-12 ***
## ONI_codeEl Niño             1.459e-01  1.129e-02  12.922  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1246 on 883 degrees of freedom
## Multiple R-squared:  0.8777, Adjusted R-squared:  0.8771 
## F-statistic:  1584 on 4 and 883 DF,  p-value: &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb102"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" tabindex="-1"></a><span class="fu">AIC</span>(lm_08)</span></code></pre></div>
<pre><code>## [1] -1171.714</code></pre>
<p>Here’s the <code>{ggplot2}</code> plot:</p>
<div class="sourceCode" id="cb104"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="#cb104-1" tabindex="-1"></a><span class="co"># get the fitted values</span></span>
<span id="cb104-2"><a href="#cb104-2" tabindex="-1"></a>ln_fit <span class="ot">&lt;-</span> lm_08<span class="sc">$</span>coeff[<span class="dv">1</span>] <span class="sc">+</span> lm_08<span class="sc">$</span>coeff[<span class="dv">2</span>] <span class="sc">*</span> NOAA2<span class="sc">$</span>YrMn <span class="sc">+</span> lm_08<span class="sc">$</span>coeff[<span class="dv">3</span>] <span class="sc">*</span> NOAA2<span class="sc">$</span>YrMn<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb104-3"><a href="#cb104-3" tabindex="-1"></a>n_fit <span class="ot">&lt;-</span> (lm_08<span class="sc">$</span>coeff[<span class="dv">1</span>] <span class="sc">+</span> lm_08<span class="sc">$</span>coeff[<span class="dv">4</span>]) <span class="sc">+</span> lm_08<span class="sc">$</span>coeff[<span class="dv">2</span>] <span class="sc">*</span> NOAA2<span class="sc">$</span>YrMn <span class="sc">+</span> lm_08<span class="sc">$</span>coeff[<span class="dv">3</span>] <span class="sc">*</span> NOAA2<span class="sc">$</span>YrMn<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb104-4"><a href="#cb104-4" tabindex="-1"></a>en_fit <span class="ot">&lt;-</span> (lm_08<span class="sc">$</span>coeff[<span class="dv">1</span>] <span class="sc">+</span> lm_08<span class="sc">$</span>coeff[<span class="dv">5</span>]) <span class="sc">+</span> lm_08<span class="sc">$</span>coeff[<span class="dv">2</span>] <span class="sc">*</span> NOAA2<span class="sc">$</span>YrMn <span class="sc">+</span> lm_08<span class="sc">$</span>coeff[<span class="dv">3</span>] <span class="sc">*</span> NOAA2<span class="sc">$</span>YrMn<span class="sc">^</span><span class="dv">2</span></span></code></pre></div>
<div class="sourceCode" id="cb105"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" tabindex="-1"></a><span class="co"># ggplot2 plot with fitted values line</span></span>
<span id="cb105-2"><a href="#cb105-2" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> NOAA2, <span class="fu">aes</span>(<span class="at">x =</span> YrMn, <span class="at">y =</span> T_LandOcean)) <span class="sc">+</span> </span>
<span id="cb105-3"><a href="#cb105-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> NOAA2<span class="sc">$</span>YrMn, <span class="at">y =</span> ln_fit), <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">linewidth =</span> <span class="fl">1.0</span>) <span class="sc">+</span></span>
<span id="cb105-4"><a href="#cb105-4" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> NOAA2<span class="sc">$</span>YrMn, <span class="at">y =</span> n_fit), <span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">linewidth =</span> <span class="fl">1.0</span>) <span class="sc">+</span></span>
<span id="cb105-5"><a href="#cb105-5" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> NOAA2<span class="sc">$</span>YrMn, <span class="at">y =</span> en_fit), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linewidth =</span> <span class="fl">1.0</span>) <span class="sc">+</span></span>
<span id="cb105-6"><a href="#cb105-6" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> NOAA2, <span class="fu">aes</span>(<span class="at">x=</span>YrMn, <span class="at">y=</span>T_LandOcean, <span class="at">color =</span> ONI_code), <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb105-7"><a href="#cb105-7" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> NOAA2, <span class="fu">aes</span>(<span class="at">x=</span>YrMn, <span class="at">y=</span>T_LandOcean), <span class="at">color =</span> <span class="st">&quot;black&quot;</span>,<span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">2</span> ) <span class="sc">+</span></span>
<span id="cb105-8"><a href="#cb105-8" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;gray&quot;</span>, <span class="st">&quot;red&quot;</span>),</span>
<span id="cb105-9"><a href="#cb105-9" tabindex="-1"></a>                     <span class="at">limits =</span> <span class="fu">c</span>(<span class="st">&quot;La Niña&quot;</span>, <span class="st">&quot;Neutral&quot;</span>, <span class="st">&quot;El Niño&quot;</span>)) <span class="sc">+</span> </span>
<span id="cb105-10"><a href="#cb105-10" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">1960</span>, <span class="dv">2025</span>, <span class="at">by =</span> <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb105-11"><a href="#cb105-11" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">1.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.25</span>), </span>
<span id="cb105-12"><a href="#cb105-12" tabindex="-1"></a>                     <span class="at">minor_breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb105-13"><a href="#cb105-13" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">&quot;NOAA Global Average Temperature Anomalies (&quot;</span>,<span class="st">&quot;°&quot;</span>,<span class="st">&quot;C)&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;&quot;</span>), </span>
<span id="cb105-14"><a href="#cb105-14" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Land + Ocean&quot;</span>) <span class="sc">+</span> </span>
<span id="cb105-15"><a href="#cb105-15" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-51-1.png" width="2100" /></p>
<p>And the residual diagnostic plots:</p>
<div class="sourceCode" id="cb106"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="#cb106-1" tabindex="-1"></a><span class="co"># regression diagnostics</span></span>
<span id="cb106-2"><a href="#cb106-2" tabindex="-1"></a>oldpar <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb106-3"><a href="#cb106-3" tabindex="-1"></a><span class="fu">plot</span>(lm_08, <span class="at">which=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>))</span>
<span id="cb106-4"><a href="#cb106-4" tabindex="-1"></a><span class="fu">acf</span>(lm_08<span class="sc">$</span>residuals)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-52-1.png" width="2100" /></p>
<div class="sourceCode" id="cb107"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" tabindex="-1"></a><span class="fu">par</span>(oldpar)</span></code></pre></div>
<p>Except for the autocorrelation in the residuals, these are the
“best-looking” plots we’ve seen. The AIC values confirm that
<code>lm_08</code> fits the data better than the earlier models:</p>
<div class="sourceCode" id="cb108"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb108-1"><a href="#cb108-1" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(<span class="fu">AIC</span>(lm_01), <span class="fu">AIC</span>(lm_03), <span class="fu">AIC</span>(lm_08)))</span></code></pre></div>
<pre><code>## [1]  -803.5893  -907.2618 -1171.7138</code></pre>
<p>And this is also confirmed by the ANOVA results:</p>
<div class="sourceCode" id="cb110"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" tabindex="-1"></a><span class="co"># anova</span></span>
<span id="cb110-2"><a href="#cb110-2" tabindex="-1"></a><span class="fu">anova</span>(lm_07, lm_08)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: T_LandOcean ~ poly(YrMn, 2, raw = TRUE)
## Model 2: T_LandOcean ~ poly(YrMn, 2, raw = TRUE) + ONI_code
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    885 16.303                                  
## 2    883 13.709  2    2.5932 83.513 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb112"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" tabindex="-1"></a><span class="fu">anova</span>(lm_01, lm_08)</span></code></pre></div>
<pre><code>## Analysis of Variance Table
## 
## Model 1: T_LandOcean ~ YrMn
## Model 2: T_LandOcean ~ poly(YrMn, 2, raw = TRUE) + ONI_code
##   Res.Df    RSS Df Sum of Sq      F    Pr(&gt;F)    
## 1    886 20.893                                  
## 2    883 13.709  3    7.1832 154.22 &lt; 2.2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb114"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="#cb114-1" tabindex="-1"></a><span class="co"># residual grouped box plot</span></span>
<span id="cb114-2"><a href="#cb114-2" tabindex="-1"></a>opar <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb114-3"><a href="#cb114-3" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">residuals</span>(lm_01) <span class="sc">~</span> NOAA<span class="sc">$</span>ONI_code, <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb114-4"><a href="#cb114-4" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">residuals</span>(lm_02) <span class="sc">~</span> NOAA<span class="sc">$</span>ONI_code, <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb114-5"><a href="#cb114-5" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">residuals</span>(lm_08) <span class="sc">~</span> NOAA<span class="sc">$</span>ONI_code, <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-55-1.png" width="2100" /></p>
<div class="sourceCode" id="cb115"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" tabindex="-1"></a><span class="fu">par</span>(opar)</span></code></pre></div>
<p>As was the case for the linear model, the dummy-variable polynomial
model eliminated the ENSO-state related residual bias.</p>
<p><a href="regression2.html">[Back to top]</a></p>
</div>
</div>
<div id="a-regression-model-with-autocorrelated-residuals"
class="section level1" number="7">
<h1><span class="header-section-number">7</span> A regression model with
autocorrelated residuals</h1>
<p>There is one remaining issue: the residual are autocorrelated. This
is not really a surprise, either looking at the data or considering what
ENSO SST variability is all about. However, the autocorrelation does
violate the OLS assumptions. The autocorrelation can be explicitly
accounted for (and hopefully removed) by simultaneously fitting a
“Box-Jenkins” type of time series model to the data while fitting the
polynomial dummy-variable regression. This can be accomplished using the
‘arima()’ function from the base <code>{stats}</code> package. The
process requires a little more set-up, but is not difficult.</p>
<p>Box-Jenkins, or “ARIMA” (autoregressive integrated moving-average)
models are a topic in themselves, but they basically related the current
value of a time series to its previous values, and to the current and
previous values of “innovations” or “exogenous shocks”. They thus can
represent both “memory” in a system as well as current perturbations to
its state. In the case of ENSO, this sounds like the memory incorporated
by the simple thermal inertia of sea water displayed by the slow changes
in SST anomalies, as will as the faster current and previous
interactions with the atmosphere.</p>
<div id="set-up" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> Set up</h2>
<p>To use the <code>arima()</code> function to fit a model that includes
autoregressive and moving-average terms as well as the polynomial dummy
variables, we have to make the dummy variables manually:</p>
<div class="sourceCode" id="cb116"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb116-1"><a href="#cb116-1" tabindex="-1"></a><span class="co"># make the dummy variables</span></span>
<span id="cb116-2"><a href="#cb116-2" tabindex="-1"></a>dum_ln <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">length</span>(NOAA<span class="sc">$</span>YrMn))</span>
<span id="cb116-3"><a href="#cb116-3" tabindex="-1"></a>dum_n <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">length</span>(NOAA<span class="sc">$</span>YrMn))</span>
<span id="cb116-4"><a href="#cb116-4" tabindex="-1"></a>dum_en <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">0</span>, <span class="fu">length</span>(NOAA<span class="sc">$</span>YrMn))</span>
<span id="cb116-5"><a href="#cb116-5" tabindex="-1"></a>dum_ln[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;La Niña&quot;</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb116-6"><a href="#cb116-6" tabindex="-1"></a>dum_n[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;Neutral&quot;</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb116-7"><a href="#cb116-7" tabindex="-1"></a>dum_en[NOAA<span class="sc">$</span>ONI_code <span class="sc">==</span> <span class="st">&quot;El Niño&quot;</span>] <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb116-8"><a href="#cb116-8" tabindex="-1"></a><span class="co"># head(cbind(dum_ln, dum_n, dum_en), 30)</span></span></code></pre></div>
<p>Note that we made dummy variables for all three ENSO states, but only
two will be included in the model to avoid collinearity. Next, make a
data frame of the the regression predictors, <code>xreg</code>:</p>
<div class="sourceCode" id="cb117"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" tabindex="-1"></a><span class="co"># make regression data frame</span></span>
<span id="cb117-2"><a href="#cb117-2" tabindex="-1"></a>xreg <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(NOAA<span class="sc">$</span>YrMn, NOAA<span class="sc">$</span>YrMn<span class="sc">^</span><span class="dv">2</span>, dum_n, dum_en) <span class="co"># note: leave dum_ln out</span></span>
<span id="cb117-3"><a href="#cb117-3" tabindex="-1"></a><span class="fu">names</span>(xreg) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;YrMn&quot;</span>, <span class="st">&quot;YrMn^2&quot;</span>, <span class="st">&quot;Neutral&quot;</span>, <span class="st">&quot;El Niño&quot;</span>)</span>
<span id="cb117-4"><a href="#cb117-4" tabindex="-1"></a><span class="fu">head</span>(xreg)</span></code></pre></div>
<pre><code>##       YrMn  YrMn^2 Neutral El Niño
## 1 1950.000 3802500       0       0
## 2 1950.083 3802825       0       0
## 3 1950.167 3803150       0       0
## 4 1950.250 3803475       0       0
## 5 1950.333 3803800       0       0
## 6 1950.417 3804125       0       0</code></pre>
</div>
<div id="time-series-regression-model" class="section level2"
number="7.2">
<h2><span class="header-section-number">7.2</span> Time-series
regression model</h2>
<p>Next, the time-series regression. There is a regular set of
procedures for iteratively determining the form of the ARIMA model
(model identification), fitting the model (estimation), and diagnostic
checking that are beyond this example. Here, it looks like an ARMA(2,2)
(two autoregressive terms, two moving average terms) will be apt.</p>
<div class="sourceCode" id="cb119"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" tabindex="-1"></a><span class="co"># time series regression, AR(2) and MA(2)</span></span>
<span id="cb119-2"><a href="#cb119-2" tabindex="-1"></a>tsreg_01 <span class="ot">&lt;-</span> <span class="fu">arima</span>(NOAA<span class="sc">$</span>T_LandOcean, <span class="at">order =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">0</span>, <span class="dv">2</span>), <span class="at">xreg =</span> xreg, <span class="at">include.mean =</span> <span class="cn">TRUE</span>)</span>
<span id="cb119-3"><a href="#cb119-3" tabindex="-1"></a>tsreg_01</span></code></pre></div>
<pre><code>## 
## Call:
## arima(x = NOAA$T_LandOcean, order = c(2, 0, 2), xreg = xreg, include.mean = TRUE)
## 
## Coefficients:
##          ar1     ar2     ma1      ma2  intercept     YrMn  YrMn^2  Neutral  El Niño
##       0.0998  0.5490  0.3883  -0.1113   686.0882  -0.7059   2e-04   0.0269   0.0785
## s.e.  0.1284  0.1097  0.1336   0.0701    69.5833   0.0701   0e+00   0.0146   0.0188
## 
## sigma^2 estimated as 0.009081:  log likelihood = 827.13,  aic = -1634.26</code></pre>
<p>Check the residuals using a function from the <code>{forecast}</code>
package:</p>
<div class="sourceCode" id="cb121"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" tabindex="-1"></a><span class="fu">checkresiduals</span>(tsreg_01, <span class="at">test =</span> <span class="st">&quot;LB&quot;</span>, <span class="at">lag =</span> <span class="dv">12</span>)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-59-1.png" width="2100" /></p>
<pre><code>## 
##  Ljung-Box test
## 
## data:  Residuals from ARIMA(2,0,2) with non-zero mean
## Q* = 6.407, df = 8, p-value = 0.6017
## 
## Model df: 4.   Total lags used: 12</code></pre>
<p>The Ljung-Box test examines the null hypothesis that the
autocorrelation of the residual is 0.0. Here the large value of
<code>Q*</code> and the large <em>p</em>-value suggest that this
hypothesis cannot be rejected.</p>
<p>Get the fitted values:</p>
<div class="sourceCode" id="cb123"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" tabindex="-1"></a><span class="co"># list the coefficients of the model</span></span>
<span id="cb123-2"><a href="#cb123-2" tabindex="-1"></a>tsreg_01<span class="sc">$</span>coef</span></code></pre></div>
<pre><code>##           ar1           ar2           ma1           ma2     intercept          YrMn        YrMn^2 
##  9.978632e-02  5.490413e-01  3.883496e-01 -1.112845e-01  6.860882e+02 -7.059136e-01  1.814731e-04 
##       Neutral       El Niño 
##  2.685890e-02  7.847971e-02</code></pre>
<div class="sourceCode" id="cb125"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" tabindex="-1"></a><span class="co"># the intercept is the 5-th term in the model</span></span>
<span id="cb125-2"><a href="#cb125-2" tabindex="-1"></a>c1 <span class="ot">&lt;-</span> <span class="dv">5</span></span></code></pre></div>
<div class="sourceCode" id="cb126"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" tabindex="-1"></a><span class="co"># fitted values</span></span>
<span id="cb126-2"><a href="#cb126-2" tabindex="-1"></a>ln_fit <span class="ot">&lt;-</span> tsreg_01<span class="sc">$</span>coef[c1] <span class="sc">+</span> tsreg_01<span class="sc">$</span>coef[c1 <span class="sc">+</span> <span class="dv">1</span>] <span class="sc">*</span> NOAA2<span class="sc">$</span>YrMn <span class="sc">+</span> tsreg_01<span class="sc">$</span>coef[c1 <span class="sc">+</span> <span class="dv">2</span>] <span class="sc">*</span> NOAA2<span class="sc">$</span>YrMn<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb126-3"><a href="#cb126-3" tabindex="-1"></a>n_fit <span class="ot">&lt;-</span> (tsreg_01<span class="sc">$</span>coef[c1] <span class="sc">+</span> tsreg_01<span class="sc">$</span>coef[c1 <span class="sc">+</span> <span class="dv">3</span>]) <span class="sc">+</span> tsreg_01<span class="sc">$</span>coef[c1 <span class="sc">+</span> <span class="dv">1</span>] <span class="sc">*</span> NOAA2<span class="sc">$</span>YrMn <span class="sc">+</span> tsreg_01<span class="sc">$</span>coef[c1 <span class="sc">+</span> <span class="dv">2</span>] <span class="sc">*</span> NOAA2<span class="sc">$</span>YrMn<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb126-4"><a href="#cb126-4" tabindex="-1"></a>en_fit <span class="ot">&lt;-</span> (tsreg_01<span class="sc">$</span>coef[c1] <span class="sc">+</span> tsreg_01<span class="sc">$</span>coef[c1 <span class="sc">+</span> <span class="dv">4</span>]) <span class="sc">+</span> tsreg_01<span class="sc">$</span>coef[c1 <span class="sc">+</span> <span class="dv">1</span>] <span class="sc">*</span> NOAA2<span class="sc">$</span>YrMn <span class="sc">+</span> tsreg_01<span class="sc">$</span>coef[c1 <span class="sc">+</span> <span class="dv">2</span>] <span class="sc">*</span> NOAA2<span class="sc">$</span>YrMn<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb126-5"><a href="#cb126-5" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">cbind</span>(ln_fit, n_fit, en_fit))</span></code></pre></div>
<pre><code>##          ln_fit      n_fit     en_fit
## [1,] -0.3647056 -0.3378467 -0.2862259
## [2,] -0.3643047 -0.3374458 -0.2858250
## [3,] -0.3639013 -0.3370424 -0.2854216
## [4,] -0.3634953 -0.3366364 -0.2850156
## [5,] -0.3630869 -0.3362280 -0.2846072
## [6,] -0.3626759 -0.3358170 -0.2841962</code></pre>
<p>The usual plot:</p>
<div class="sourceCode" id="cb128"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb128-1"><a href="#cb128-1" tabindex="-1"></a><span class="co"># ggplot2 plot with fitted values line</span></span>
<span id="cb128-2"><a href="#cb128-2" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> NOAA2, <span class="fu">aes</span>(<span class="at">x =</span> YrMn, <span class="at">y =</span> T_LandOcean)) <span class="sc">+</span> </span>
<span id="cb128-3"><a href="#cb128-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> NOAA2<span class="sc">$</span>YrMn, <span class="at">y =</span> ln_fit), <span class="at">color =</span> <span class="st">&quot;blue&quot;</span>, <span class="at">linewidth =</span> <span class="fl">1.0</span>) <span class="sc">+</span></span>
<span id="cb128-4"><a href="#cb128-4" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> NOAA2<span class="sc">$</span>YrMn, <span class="at">y =</span> n_fit), <span class="at">color =</span> <span class="st">&quot;gray&quot;</span>, <span class="at">linewidth =</span> <span class="fl">1.0</span>) <span class="sc">+</span></span>
<span id="cb128-5"><a href="#cb128-5" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> NOAA2<span class="sc">$</span>YrMn, <span class="at">y =</span> en_fit), <span class="at">color =</span> <span class="st">&quot;red&quot;</span>, <span class="at">linewidth =</span> <span class="fl">1.0</span>) <span class="sc">+</span></span>
<span id="cb128-6"><a href="#cb128-6" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> NOAA2, <span class="fu">aes</span>(<span class="at">x=</span>YrMn, <span class="at">y=</span>T_LandOcean, <span class="at">color =</span> ONI_code), <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span> </span>
<span id="cb128-7"><a href="#cb128-7" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> NOAA2, <span class="fu">aes</span>(<span class="at">x=</span>YrMn, <span class="at">y=</span>T_LandOcean), <span class="at">color =</span> <span class="st">&quot;black&quot;</span>,<span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">2</span> ) <span class="sc">+</span></span>
<span id="cb128-8"><a href="#cb128-8" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;blue&quot;</span>, <span class="st">&quot;gray&quot;</span>, <span class="st">&quot;red&quot;</span>),</span>
<span id="cb128-9"><a href="#cb128-9" tabindex="-1"></a>                     <span class="at">limits =</span> <span class="fu">c</span>(<span class="st">&quot;La Niña&quot;</span>, <span class="st">&quot;Neutral&quot;</span>, <span class="st">&quot;El Niño&quot;</span>)) <span class="sc">+</span> </span>
<span id="cb128-10"><a href="#cb128-10" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">1960</span>, <span class="dv">2025</span>, <span class="at">by =</span> <span class="dv">10</span>)) <span class="sc">+</span></span>
<span id="cb128-11"><a href="#cb128-11" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">limits =</span> <span class="fu">c</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">1.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.25</span>)</span>
<span id="cb128-12"><a href="#cb128-12" tabindex="-1"></a>                     , <span class="at">minor_breaks =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.75</span>, <span class="fl">1.25</span>, <span class="at">by =</span> <span class="fl">0.05</span>)) <span class="sc">+</span></span>
<span id="cb128-13"><a href="#cb128-13" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">&quot;NOAA Global Average Temperature Anomalies (&quot;</span>,<span class="st">&quot;°&quot;</span>,<span class="st">&quot;C)&quot;</span>, <span class="at">sep =</span> <span class="st">&quot;&quot;</span>), </span>
<span id="cb128-14"><a href="#cb128-14" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Land + Ocean&quot;</span>) <span class="sc">+</span> </span>
<span id="cb128-15"><a href="#cb128-15" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-62-1.png" width="2100" /></p>
<p>The residual diagnostic plots (note there is not time-series
equivalent of Cook’s distance)</p>
<div class="sourceCode" id="cb129"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" tabindex="-1"></a><span class="co"># residual diagnostics</span></span>
<span id="cb129-2"><a href="#cb129-2" tabindex="-1"></a>oldpar <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span>
<span id="cb129-3"><a href="#cb129-3" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(tsreg_01), tsreg_01<span class="sc">$</span>residuals)</span>
<span id="cb129-4"><a href="#cb129-4" tabindex="-1"></a><span class="fu">qqnorm</span>(tsreg_01<span class="sc">$</span>residuals)</span>
<span id="cb129-5"><a href="#cb129-5" tabindex="-1"></a><span class="fu">qqline</span>(tsreg_01<span class="sc">$</span>residuals)</span>
<span id="cb129-6"><a href="#cb129-6" tabindex="-1"></a><span class="fu">acf</span>(tsreg_01<span class="sc">$</span>residuals)</span>
<span id="cb129-7"><a href="#cb129-7" tabindex="-1"></a><span class="fu">par</span>(oldpar)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-63-1.png" width="2100" />
These look good. The AIC values suggest that the model fits better still
than the previous one, so it was worthwhile to include the ARMA
terms;</p>
<div class="sourceCode" id="cb130"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="#cb130-1" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">c</span>(<span class="fu">AIC</span>(lm_01), <span class="fu">AIC</span>(lm_08), <span class="fu">AIC</span>(tsreg_01)))</span></code></pre></div>
<pre><code>## [1]  -803.5893 -1171.7138 -1634.2587</code></pre>
<p>Here are the residual grouped box plots:</p>
<div class="sourceCode" id="cb132"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb132-1"><a href="#cb132-1" tabindex="-1"></a><span class="co"># residual grouped box plot</span></span>
<span id="cb132-2"><a href="#cb132-2" tabindex="-1"></a>opar <span class="ot">&lt;-</span> <span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>))</span>
<span id="cb132-3"><a href="#cb132-3" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">residuals</span>(lm_01) <span class="sc">~</span> NOAA<span class="sc">$</span>ONI_code, <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb132-4"><a href="#cb132-4" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">residuals</span>(lm_08) <span class="sc">~</span> NOAA<span class="sc">$</span>ONI_code, <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb132-5"><a href="#cb132-5" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="fu">residuals</span>(tsreg_01) <span class="sc">~</span> NOAA<span class="sc">$</span>ONI_code, <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>))</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-65-1.png" width="2100" /></p>
<div class="sourceCode" id="cb133"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" tabindex="-1"></a><span class="fu">par</span>(opar)</span></code></pre></div>
<p>The spread of the residuals from the time-series regression model is
clearly smaller than the others, which can be seen by simply
overplotting the residuals from <code>lm_08</code> with those from
<code>tsreg_01</code>.</p>
<div class="sourceCode" id="cb134"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="#cb134-1" tabindex="-1"></a><span class="fu">plot</span>(NOAA<span class="sc">$</span>YrMn, <span class="fu">residuals</span>(lm_08), <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;magenta&quot;</span>)</span>
<span id="cb134-2"><a href="#cb134-2" tabindex="-1"></a><span class="fu">lines</span>(NOAA<span class="sc">$</span>YrMn, tsreg_01<span class="sc">$</span>residuals, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">col =</span> <span class="st">&quot;green&quot;</span>)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-66-1.png" width="2100" /></p>
<p><a href="regression2.html">[Back to top]</a></p>
</div>
<div id="slope-of-the-polynomial-trend" class="section level2"
number="7.3">
<h2><span class="header-section-number">7.3</span> Slope of the
polynomial trend</h2>
<p>The original focus of this example was to estimate the trend in
monthly global average temperatures, and the influence of the ENSO state
on rising temperatures. However, the fact that the trend is curvilinear
complicates this, because the slopes vary over time. The slope of a
polynomial is just the first derivative. The increasing slope of the
fitted curves (which are the same, only the intercept varies) can be
gotten as follows:</p>
<div class="sourceCode" id="cb135"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" tabindex="-1"></a><span class="co"># slope is first derivative of the polynomial,</span></span>
<span id="cb135-2"><a href="#cb135-2" tabindex="-1"></a><span class="co"># If f(x) = b0 + b1 * x + b2 * x^2, then f&#39;(x) = 2 * b2 * x + b1</span></span>
<span id="cb135-3"><a href="#cb135-3" tabindex="-1"></a>c1 <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb135-4"><a href="#cb135-4" tabindex="-1"></a>slope <span class="ot">&lt;-</span> <span class="fl">2.0</span> <span class="sc">*</span> tsreg_01<span class="sc">$</span>coef[c1 <span class="sc">+</span> <span class="dv">2</span>] <span class="sc">*</span> NOAA<span class="sc">$</span>YrMn <span class="sc">+</span> tsreg_01<span class="sc">$</span>coef[c1 <span class="sc">+</span> <span class="dv">1</span>]</span>
<span id="cb135-5"><a href="#cb135-5" tabindex="-1"></a><span class="fu">plot</span>(NOAA<span class="sc">$</span>YrMn, slope, <span class="at">type =</span> <span class="st">&quot;o&quot;</span>, <span class="at">cex =</span> <span class="fl">0.5</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">xlab =</span> <span class="st">&quot;Year&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;slope (degC/Year)&quot;</span>)</span></code></pre></div>
<p><img src="regression2_files/figure-html/regression2-67-1.png" width="2100" /></p>
<p>As can be seen, the slope of the polynomial increases over time.
Here’s another perspective:</p>
<div class="sourceCode" id="cb136"><pre
class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="#cb136-1" tabindex="-1"></a>slope_1960 <span class="ot">&lt;-</span> <span class="fl">2.0</span> <span class="sc">*</span> tsreg_01<span class="sc">$</span>coef[c1 <span class="sc">+</span> <span class="dv">2</span>] <span class="sc">*</span> <span class="dv">1960</span> <span class="sc">+</span> tsreg_01<span class="sc">$</span>coef[c1 <span class="sc">+</span> <span class="dv">1</span>]</span>
<span id="cb136-2"><a href="#cb136-2" tabindex="-1"></a>slope_2020 <span class="ot">&lt;-</span> <span class="fl">2.0</span> <span class="sc">*</span> tsreg_01<span class="sc">$</span>coef[c1 <span class="sc">+</span> <span class="dv">2</span>] <span class="sc">*</span> <span class="dv">2020</span> <span class="sc">+</span> tsreg_01<span class="sc">$</span>coef[c1 <span class="sc">+</span> <span class="dv">1</span>]</span>
<span id="cb136-3"><a href="#cb136-3" tabindex="-1"></a>slope_ratio <span class="ot">&lt;-</span> (slope_2020 <span class="sc">/</span> slope_1960)</span>
<span id="cb136-4"><a href="#cb136-4" tabindex="-1"></a></span>
<span id="cb136-5"><a href="#cb136-5" tabindex="-1"></a>slopes <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(slope_1960, slope_2020, slope_ratio)</span>
<span id="cb136-6"><a href="#cb136-6" tabindex="-1"></a><span class="fu">colnames</span>(slopes) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;slope 1960&quot;</span>, <span class="st">&quot;slope_2020&quot;</span>, <span class="st">&quot;ratio&quot;</span>)</span>
<span id="cb136-7"><a href="#cb136-7" tabindex="-1"></a><span class="fu">rownames</span>(slopes) <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb136-8"><a href="#cb136-8" tabindex="-1"></a>slopes</span></code></pre></div>
<pre><code>##    slope 1960 slope_2020    ratio
## 1 0.005461036 0.02723781 4.987664</code></pre>
<p>The rate of global warming has increased about five times between
1960 and 2020!</p>
<p><a href="regression2.html">[Back to top]</a></p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
